### ISSUE TITLE
block_size > 4096

### ISSUE THREAD

**Issue by iddq** [travisgoodspeed/md380tools#10]
what is the usb backend that you use for pyUSB that can handle larger usb transfer size than 4096 bytes?

**Comment by travisgoodspeed** [comment]
libusb-1.0

**Comment by iddq** [comment]
have you modified the libusb? MAX_CTRL_BUFFER_LENGTH is 4096

libusb/os/linux_usbfs.h:#define MAX_CTRL_BUFFER_LENGTH          4096

./libusb/os/linux_usbfs.c:

        if (transfer->length - LIBUSB_CONTROL_SETUP_SIZE > MAX_CTRL_BUFFER_LENGTH)
                return LIBUSB_ERROR_INVALID_PARAM;

**Comment by travisgoodspeed** [comment]
I used libusb-1.0 on a Mac, but I didn't encounter this issue.  Please get in touch with me by email, travis at radiantmachines, and I can send you longer form notes without cluttering github issues.
