### ISSUE TITLE
arm-none-eabi-gcc command not found

### ISSUE THREAD

**Issue by webkernel** [travisgoodspeed/md380tools#103]
Hi,

I am using Debian 8.2 out-of-the-box install and after make clean diet i got this error:

arm-none-eabi-gcc command not found

Please help.

**Comment by dl8bb** [comment]
You need to install the appropriate arm compiler suite. Please take a look i.e. https://launchpad.net/gcc-arm-embedded or install the debian packages for arm build environment. 

_sudo apt-get install gcc-arm-none-eabi_

You need to have a working build environment with make, linker etc already installed.

If you don't have it, install at least the build-essential package.

_sudo apt-get install build-essential_

Just my 2 cents

**Comment by travisgoodspeed** [comment]
Close this issue when README.MD contains explicit apt-get instructions for Debian.

**Comment by webkernel** [comment]
many thanks. it worked!

**Comment by LW-Ho** [comment]
Thanks a lot. it worked!

**Comment by 1399999** [comment]
Big thanks. It worked.
