### ISSUE TITLE
Adding the ability to lock only the front keypad OR front keypad and side keys

### ISSUE THREAD

**Issue by dg9vh** [travisgoodspeed/md380tools#125]
See https://groups.google.com/forum/#!topic/md380tools/zW7tkAydKRY

**Comment by dg9vh** [comment]
Via the md380tools-menu should be switchable, how the default-lock-mechanism works.

- default behavior (only lock keypad)
- extra behavior (lock keypad as default plus side-keys PTT, P1 and P2).

Unlock as default.

**Comment by travisgoodspeed** [comment]
Merged into #370. Reopen only if there is active progress in adding such a feature.
