### ISSUE TITLE
Annoying Tone on Unused Channel

### ISSUE THREAD

**Issue by dg9vh** [travisgoodspeed/md380tools#126]
See https://groups.google.com/forum/#!topic/md380tools/zW7tkAydKRY

**Comment by dg9vh** [comment]
If turning the channel knob to unprogrammed position a loud "duuuuuut" would be emitted. This should be muted and either the last channel selected should be selected with a short message displayed for lets say 5 seconds "channel not programmed, staying on last" or only the message "unprogrammed" should stay as in stock but without this noisy tone. 

Close if configurable via md380tools-menu to be switched on and of - some people need this tone to get on place (blinds)

**Comment by travisgoodspeed** [comment]
Merged into #370. Reopen only if there is active progress in adding such a feature.

**Comment by danny1990** [comment]
I found a fix it may not be the best but it works this also works for other sounds too.

in beep.c under "beep_OSMboxPend_hook()" set

case 15: // Invalid channel beep
    return 0;

**Comment by KD4Z** [comment]
That did kill the unprogrammed channel tone.  However,  as you said, it also kills the "Roger Beep"  I made it optional in my VM to kick it around a bit.

**Comment by travisgoodspeed** [comment]
Reopening.  We'll close this when #830 is merged.
