### ISSUE TITLE
Adding an option to adjust mic gain

### ISSUE THREAD

**Issue by dg9vh** [travisgoodspeed/md380tools#127]
See https://groups.google.com/forum/#!topic/md380tools/zW7tkAydKRY

**Comment by dg9vh** [comment]
Mic-gain should be adjustable from minimum to maximum as number values from 0 to 100, maybe assisted by @aeickho 's volume-meter in https://github.com/travisgoodspeed/md380tools/commit/989b8b08972385dedd72f77d8e73a5d640dcae80

Close if functional or dismissed.

**Comment by der-stefan** [comment]
According to https://github.com/pchickey/md380-re/blob/master/datasheets/hrc5000.pdf (page 9) the C5000 has a register to set a MicVol. Or at least 4 bit to set 0dB, 6dB, 12dB or 20dB mic gain.

**Comment by travisgoodspeed** [comment]
Merged into #370. Reopen only if there is active progress in adding such a feature.
