### ISSUE TITLE
Option to edit programmed channel...

### ISSUE THREAD

**Issue by dg9vh** [travisgoodspeed/md380tools#137]
... to modify "Contact Name" in codeplug section "Channels Information". To be placed in "Utilities"  "program radio" as point after "Repeater Slot".

Close if functional

**Comment by travisgoodspeed** [comment]
This description is a bit too terse.  Could you explain the issue more clearly?

**Comment by dg9vh** [comment]
Trying to describe it step by step:

- Adding menupoint "Utilities"-"program radio"-"Change Contact Name"
- load all contacts into a list marked as "group call"
- select current Contact Name selected in codeplug as default-contact for programmed channel
- after selecting other contact write this into channel information

**Comment by travisgoodspeed** [comment]
The feature is certainly reasonable to add.  Any volunteers to write the patch?

**Comment by mach327** [comment]
If I understand correctly, the idea is to be able to edit a digital channels contact/txgroup from the front panel. That would seem to be a critical feature for programming digital channels from the front panel.

**Comment by travisgoodspeed** [comment]
Merged into #370. Reopen only if there is active progress in adding such a feature.
