### ISSUE TITLE
Request: change or add additional timeout options under backlight settings menu.

### ISSUE THREAD

**Issue by pricead** [travisgoodspeed/md380tools#144]
By default, the highest backlight setting (other than forcing always on) is only 15 seconds. On longer QSOs, this ends up with the display timing out in the middle of receiving audio. Would it be possible to change or add options for 30/60/90 seconds, so that the display could be visible during the entire period of reception? An alternative would be to change the firmware so that the timeout doesn't start to run until after the end of reception. 

Issue will be solved if the display remains on for the entire length of reception.

**Comment by travisgoodspeed** [comment]
Merged into #370. Reopen only if there is active progress in adding such a feature.
