### ISSUE TITLE
Scrolling zone with the up and down arrow during receiving

### ISSUE THREAD

**Issue by IZ6MAF** [travisgoodspeed/md380tools#147]
Zone selection during reception.
Using the transceiver, traveling with the car, we have continually the need to move from one zone ( 1st repeater ) to another zone ( 2 ° repeater ) to a third zone and so on (only in Italy we have more than 69 different zone). 
The current procedure for changing the zone  is long rather laborious, and must be done by pressing the following keys: "confirm" -> Arrow down -> Arrow down -> "confirm" -> "Multiple Arrow Up & Down to zone selection" -> "confirm".
As when the unit is receiving the arrow buttons on the keyboard have no function, please can you add a tool that permits to us the zone selection function pushing the keyboard arrow buttons down and up during the reception?
Thank you very much
'73 Paolo IZ6MAF

**Comment by M0IVQ** [comment]
One of the side buttons can be programmed to increment the zone on stock firmware but only in one direction.

**Comment by IZ6MAF** [comment]
Yes I know, but to go up one zone I need to go down 69 zone, it is not really practical !!!

**Comment by IZ6MAF** [comment]
Yes I know, but to go up one zone i must go down 69 zone, it's not really pratical

**Comment by M0IVQ** [comment]
Sorry, my comment was meant for informational purposes as may assist with patching to enable scrolling up and down rather than just down.

**Comment by travisgoodspeed** [comment]
Merged into #370. Reopen only if there is active progress in adding such a feature.
