### ISSUE TITLE
Firmware Download Bug, Silent Failure

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/md380tools#156]
Since #153, the Makefile silently fails if a download is the wrong size according to `du`.

Close this issue when:
- [x] Download failures cause a make failure, instead of just quiet file deletion.
- [x] Check filesize with `ls -l` instead of `du`, which varies by the file size. [used `find` instead]

I'll assign @d235j when he accepts his damned commit rights.

**Comment by ajorg** [comment]
Accidentally posted this to the pull-request discussion instead of here:
> du is meant to tell you how much of your disk the file is actually using, it's not meant to tell you the size of the file. stat -c %s is a better way to do that.

**Comment by ajorg** [comment]
Should also use curl's --fail option to make it give you a non-zero exit code on failure.

**Comment by d235j** [comment]
@ajorg yeah, as a first pass I didn't do much cleanup of the already-existing download code. Among other things I dislike the hardcoded list in the Makefile — I'd rather pull the information from a separate text file.

@ajorg: stat -c %s is GNU behaviour and does not work on Mac OS X; I will investigate a better solution.

**Comment by d235j** [comment]
@ajorg any objections to using ```wc -c <file```?

**Comment by ajorg** [comment]
@d235j not for files this small. for larger files I'd object strenuously.

**Comment by d235j** [comment]
@ajorg good point, not sure how I missed that.. Think I'll use ```find filename -a -size Nc``` instead.

**Comment by d235j** [comment]
Should be fixed as of c795189. I will await testing by others before closing this issue.

**Comment by d235j** [comment]
As of  e076985, the Makefile is mostly generic and reads firmware information from a separate text file. Additionally, both the filesize and sha256 hashes are checked.

**Comment by d235j** [comment]
Closing -- please comment or open a new issue if there are further problems.
