### ISSUE TITLE
Faster navigation in contacts possible?

### ISSUE THREAD

**Issue by RipperFox** [travisgoodspeed/md380tools#158]
It would be very helpful if one could use numpad to scroll through the contacts list.
E.g. '1'/'7' could go up/down page-wise,  '2'/'8' could scroll up/down 100 entries, etc.

Also some kind of key-repeat on the up/down keys would be nice.

**Comment by travisgoodspeed** [comment]
Merged into #370. Reopen only if there is active progress in adding such a feature.
