### ISSUE TITLE
Use of messages function

### ISSUE THREAD

**Issue by trolfe** [travisgoodspeed/md380tools#159]
I am attempting to capture messages as they arrive using the messages
 function. There seems to be an issue in that sometimes when a new
 message arrives the message list is corrupted - possible replacing
 some messages with 0 values. Also the message list returned may be
 trunkated losing some messages.

 Also the messages function returns all the messages on the radio (even
 after the message list is cleared on the radio) - the message list
restarts at the top of the list when they are cleared though.

 I believe another approach may just be to use dmesgtail type of
 function. However looking at the data blocks after the SMS header the
 actual text of the message seems to start part way through the data
 blocks (and not consistent in where it starts). I have the description
 of the message block in dmr.c as attached. Is there a fuller
 description of the data blocks available?
![sms_block](https://cloud.githubusercontent.com/assets/20227607/16492971/b6a8e3a6-3edb-11e6-92b5-38588d280b26.PNG)

**Comment by travisgoodspeed** [comment]
The dmesg tail is showing internal test functions of an SMS header, with UTF16 text inside.  This is just a raw incoming frame, and you'll need to parse it with a script of some sort.

I started #161 to track the inclusion of deleted messages in the list.

Closing this issue as a support request.
