### ISSUE TITLE
`md380-tool messages` includes deleted messages.

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/md380tools#161]
The `md380-tool messages` command includes deleted messages, when it should only include messages which have not been deleted.  Figure out how the deleted messages are marked, and then exclude them from the list.

This issue came from #159.

**Comment by ea** [comment]
Looking at the SPI dump and messing around, I can now successfully resurrect deleted messages, place new ones and delete existing ones by modifying spi flash directly. 

So I'll take a stab at this. 

Basically, each group of messages (inbox,sent...) is preceded by a table of 50 4byte words which correspond to each 0x124 byte message slot. Each word carries some metadata about the message (deleted or not, read or not, index... ).
