### ISSUE TITLE
Feature: End-of-call chirp

### ISSUE THREAD

**Issue by nivex** [travisgoodspeed/md380tools#162]
When a received call ends, play a short chirp on the speaker as an audible cue to the user who might not be looking at the handset (eg: using a speaker mic).

Some folk I've talked to in the area miss the "courtesy tone" of the local analog repeaters. This would be a way to replicate that functionality.

**Comment by aeickho** [comment]
please tray
    Radio Settings->Tones/Alerts->All Tones -> Turn On

i think this solved your wish.

**Comment by travisgoodspeed** [comment]
@aeickho Does this give an ending tone for you?  On my radios, it only gives the initial chirp, not one after the end of the broadcast.

**Comment by aeickho** [comment]
@travisgoodspeed 
I gave you a short movie via twitter sent with respect to the behavior.

I'm unsure if we're talking about the same.

good night from Germany

**Comment by travisgoodspeed** [comment]
My mistake; this feature does already exist.  Closing the issue.

**Comment by nivex** [comment]
I just got a chance to flash the most current firmware this morning. I have verified that All Tones is turned on. I do not hear any tone when the far end ceases their transmission.

**Comment by aeickho** [comment]
I'll will check it... Mybee an Problem included by the last chage re #130?

**Comment by aeickho** [comment]
No ... It works fine on my Radios with head of Master

**Comment by aeickho** [comment]
Is there an misunderstanding?

**Comment by nivex** [comment]
For reference, this needs the "Ch Free Indication Tone" checkbox set in the CPS.
