### ISSUE TITLE
dmr.c question about (priv)squelch_hook()

### ISSUE THREAD

**Issue by aeickho** [travisgoodspeed/md380tools#166]
on  src/dmr.c

* Line:138 
   dmr_before_squelch(); 
  please descriptive short your intention, I have no idea about the function.

* Line :140 
  dmr_apply_squelch()
  is:
  uint8_t md380_OSMboxPost(OS_EVENT *pevent, void *pmsg);
should I change that?

**Comment by travisgoodspeed** [comment]
@aeickho I've pushed what I know to the repo.  Feel free to rename any functions that I've misnamed, such as md380_OSMboxPost() in this example.

Close this issue if that's sufficient.

Cheers,
--Travis
