### ISSUE TITLE
Forward port patches to v2.034 / MD446 hardware support.

### ISSUE THREAD

**Issue by rct** [travisgoodspeed/md380tools#17]
Forward port the "scanning" patches, listen to all talkgroups and all private calls, to the current firmware version D2.034.

The current patches are against firmware version 2.032.

Issue dded for tracking/documentation purposes.

**Comment by travisgoodspeed** [comment]
Is a change log available from Tytera that describes what's new in 2.034?

**Comment by selabnayr** [comment]
http://www.va3xpr.net/programming-software-firmware/ has a good set of firmwares, and it looks like the Operation.doc.pdf file in the archives has a changelog.

**Comment by selabnayr** [comment]
Ah, changelog format is a bit weird. The bolded section is what's new since the previous release.

**Comment by travisgoodspeed** [comment]
So the new features in bold are as follows:
```
13. Correct spelling of repeatar in Utilities-program radio-repeatar to repeater
14. Solve the wrong display when deleting entry from Missed List. When the
last entry is deleted the screen displays:“??? ??? ?”
15. Solve the problem when we program the radio, there will be some data missing.
```

I'm pushing a patch for 13 in a minute.  Are 14 or 15 worth the trouble of porting the scripts and abandoning the current symbols, or should we wait another version?

**Comment by rct** [comment]
@selabnayr thanks for the clarification.
@travisgoodspeed - maybe not, though would like to find out what _"15. Solve the problem when we program the radio, there will be some data missing."_ really means.

**Comment by travisgoodspeed** [comment]
2.032 has some really janky bit-bang code to read and write the SPI Flash.   I'm guessing that it gave them trouble and they made a minor change.

I'm leaving this issue open for now, because we will need to be version-agnostic in the future, but for now I'll continue to use absolute addresses.  I'll go back to clean things up after the LCD display is better understood.

**Comment by travisgoodspeed** [comment]
So I really, truly wanted to label this as WONTFIX and call it a day, but it looks like we need 2.034 to support the MD446.  Version 2.032 will flash to the MD446, but the keypad is incompatible and the menu items are unreachable.

I'll buy a six pack of good beer for whomever can automate the symbol transition from 2.032 to 2.034, even if a few symbols have to manually patched up afterward.

**Comment by travisgoodspeed** [comment]
Looks like 2.034 is built separately for the MD446 and MD380, so there won't be one version that's compatible with both.  Moving this back to wontfix.
