### ISSUE TITLE
Firmware D13.14

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/md380tools#170]
There's a second firmware release for the new hardware.  Please close this issue when `firmware/Makefile` fetches it from an Archive.org mirror.

Assigning @d235j.

**Comment by DL9LBG** [comment]
... and it reanimated my dead rt8(gps) \o/

**Comment by d235j** [comment]
@DL9LBG where has this firmware been posted?

**Comment by DL9LBG** [comment]
Retevis has sent it directly per E-Mail. View this blogpost http://blog.retevis.com/firmware-update-rt3-rt8/  Ask for "suited firmware update" and they'll send it to you.

**Comment by d235j** [comment]
Resolved in d4109411e4ea22d132d4eb73c8787c973bcefb57.
