### ISSUE TITLE
Verify Radare2 syntax changes

### ISSUE THREAD

**Issue by d235j** [travisgoodspeed/md380tools#172]
Since I'm not yet too familiar with Radare2 script syntax, can someone else (preferable @aeickho) look c008ea7fd026630deb08ee3df85fae013b57845a over? As best as I can tell, af+ commands without a length provided silently fail.
The lengths I provided were output by af and I'm not sure whether they're accurate.
Thanks!

**Comment by d235j** [comment]
Also 4144633d88a0d0a004e3b832fe7899cbff2671a6

**Comment by d235j** [comment]
Looks good.

**Comment by aeickho** [comment]
know my radare2 is also minimal. also I do not know if I use it correctly.

the length of the functions I determine also rode the "af" komando then look after but if it's true. not always it finds the correct length.
 
not nice in the use of "af +" there is no crossref which there is in "af".
