### ISSUE TITLE
Send SMS via USB  

### ISSUE THREAD

**Issue by aeickho** [travisgoodspeed/md380tools#190]
Close this Issue when 

[  ] send sms via USB

is possible

**Comment by travisgoodspeed** [comment]
When testing this, you should expect hardware trouble from the transmission interacting with the USB cable.  I've had best luck with a laptop running from battery power, with a ferrite choke on the USB cable.

**Comment by mach327** [comment]
Merging into #370. Reopen when/if progress is made towards this.
