### ISSUE TITLE
make flash fails fatal error

### ISSUE THREAD

**Issue by davetelling** [travisgoodspeed/md380tools#191]
Sigh... I'm trying to make the firmware flash in Mint Linux. If I run:
sudo make flash or
sudo make clean flash
I get this error both times:
/usr/lib/gcc/arm-none-eabi/4.9.3/include/stdint.h:9:26: fatal error: stdint.h: No such file or directory
 # include_next <stdint.h>
I look in /usr/lib/gcc/arm-none-eabi/4.9.3/include/ and there is, in fact, a file called stdint.h
So, why the fatal error?

**Comment by iball** [comment]
Did you install all of the following?  

apt-get install gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi \
                libusb-1.0 python-usb

**Comment by davetelling** [comment]
yes, I installed as the webpage showed. I mainly don't understand why the script says that the file doesn't exist when it actually does.

**Comment by davetelling** [comment]
I'm an idiot somehow, my blurry eyes totally missed libnewlib-arm-none-eabi package!
installing that fixed the problem. Consider my forehead slapped! Doh!
