### ISSUE TITLE
Last heard list 

### ISSUE THREAD

**Issue by aeickho** [travisgoodspeed/md380tools#198]
I wish me:
  An List with the last $x heard dmr user ...

"Last heard",  "dmr user id" , "channel"

Close this Issue when functionality is added.

**Comment by hamradioPRC** [comment]
It would help me alot as opposed with others

**Comment by aeickho** [comment]
+ last gps position of the radio + distance info

**Comment by mach327** [comment]
Merging into #370. Reopen when/if progress is made towards this.
