### ISSUE TITLE
Codeplug Headers

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/md380tools#2]
TYT's official editor for the MD380 issues its codeplugs as `.RDT` files, which are just a thin DFU header applied to the binary codeplug.

Close this issue when `md380-dfu` properly creates and reads the headers when the extension is `.rdt`.

**Comment by rct** [comment]
FYI.  extracting a .img from a .rdt is straightforward:
* .rdt files are 565 bytes longer.
* There is 549 bytes at the beginning that identifies the radio/version of CPS software.
  * the bytes that indicate md-380 vs. cs700 start around 0x115.
* There is an extra 16 bytes at the end of the .rdt.

Convert .rdt to .img
```
rdtdata = open("file.rdt",'rb').read()
imgdata = rdtdata[549:len(data)-16]
```
