### ISSUE TITLE
Navigate the menu with direct item number entry

### ISSUE THREAD

**Issue by Astroscope** [travisgoodspeed/md380tools#203]
As most (sub)menu items are numbered, it would be very nice to navigate them not only with up/down&confirm but also with direct item number entry. For an example: choose Messages with up/down&confirm, then press 3 to directly choose Quick Text and so on. That was done in some old cellphones and was very useful.

**Comment by aeickho** [comment]
yes this is an nice wish ... but reverse engineering from a gui is not easy. 

 And participate so few peoble on the research.

**Comment by mach327** [comment]
Merging into #370. Reopen when/if progress is made towards this.
