### ISSUE TITLE
Users.CSV Update Build Procedure (Documentation)

### ISSUE THREAD

**Issue by iball** [travisgoodspeed/md380tools#204]
When executing "sudo make flashdb" if there is already a users.csv file present in db it will use it instead of downloading a fresh copy pulled from the DMR-MARC database.

See screenshot for output.

![md380flashdb](https://cloud.githubusercontent.com/assets/1633825/17177752/76510e48-53d8-11e6-9303-450ece1b463e.JPG)

**Comment by iball** [comment]
As you can see, a sudo make clean does not delete the users.csv file in the db directory.

![md380flashdb_2](https://cloud.githubusercontent.com/assets/1633825/17177981/48cd2fb4-53d9-11e6-8cb0-fdd08914ac29.JPG)

**Comment by travisgoodspeed** [comment]
This is intentional, so that development can be performed offline without erasing the database.  Similarly, we don't delete the firmware images on a global `make clean`, as you might need them for the next build.  You can always grab the new database by running `make clean all` in `db/`.

Closing issue.

--KK4VCZ

**Comment by iball** [comment]
OK, I completely understand this however perhaps something in the README about it should be noted?
Otherwise unsuspecting users not familiar with it - not all hams are real familiar with Linux and make tools - will never get users.csv updated properly and possibly open future tickets on "ID not found in users.csv".

**Comment by travisgoodspeed** [comment]
Fair enough.  Reopening the issue.

Close this issue when the README.md mentions the database rebuild procedure.

**Comment by iball** [comment]
@travisgoodspeed I wrote a small blurb about it.

**Comment by aeickho** [comment]
@iball your patch #205 ... please remove the sudo ....  
Do you know https://github.com/travisgoodspeed/md380tools/blob/master/99-md380.rules
with this rule anybody on your system have access to flash the radio
this is also an note for the documentation

**Comment by iball** [comment]
@aeickho Ah yes, excellent point.  
I'll work on those changes and include the blurb about ensuring that the 99-md380.rules is placed in /etc/udev/rules.d/ and remove the sudo.

**Comment by iball** [comment]
OK, changes made.  Please review when you get time.

**Comment by travisgoodspeed** [comment]
Build instructions have been updated with 7f4b052.  Closing issue.
