### ISSUE TITLE
Zones from 16 to 32

### ISSUE THREAD

**Issue by M6NBP** [travisgoodspeed/md380tools#206]
Can the zones be made bigger from 16 to 32 or larger?

**Comment by travisgoodspeed** [comment]
How would you turn the channel knob past 16?  It has a fixed number of positions.

**Comment by M6NBP** [comment]
Good thinking bat man lol
This will have to wait for newer type off radios down the line.

**Comment by travisgoodspeed** [comment]
Cool.  Closing issue.
