### ISSUE TITLE
Hytera (Software Developers)

### ISSUE THREAD

**Issue by M6NBP** [travisgoodspeed/md380tools#207]
I was wondering if anyone was working on Hytera?

After a few contacts with Hytera its looking like they will permit 3rd party software to be used.

I have set up a  website etc to see if we can get this off the group as I have no Software Development skills and am hopping ones in this group might be willing.

Am adding the link (Put please remove if breaking the rules)
https://hamradio.joomla.com/lobby-hytera

Many thanks

**Comment by travisgoodspeed** [comment]
I wish you the best of luck, but this is an issue tracker and not a message board.

Closing issue, as there's no software or documentation work to do.
