### ISSUE TITLE
Stock scrolling/marquee feature missing after installing experimental firmware

### ISSUE THREAD

**Issue by burnersk** [travisgoodspeed/md380tools#210]
With stock firmware version D3.20 of Tytera MD-380 there was a scolling/marquee feature of texts like current selected zone and channel (on the "home screen").

Today I cloned this Git repository and the scrolling/marquee feature is gone.

During the make process my (previously installed stock) firmware was downloaded. So I assume that the "new features" introduced with that stock firmware update will be persists with the experimental firmware since it is "just" a patch onto the stock firmware.

Unfortunately the channel and zone texts on the home screen does not scroll/marquee anymore.

Radio Version dialog shows: MD380Tools Ver: `2016-08-01`, CP Ver: `V01.36`

**Comment by travisgoodspeed** [comment]
Our firmware is currently patched against 2.032.  We're in the process of porting our patches to 3.20, and this effort is being tracked in other issues. 

Closing this issue as a duplicate. See #181 and others.
