### ISSUE TITLE
Editing DMRId in D013.020 not working properly

### ISSUE THREAD

**Issue by dg9vh** [travisgoodspeed/md380tools#220]
The editing of the DMRId withing the D013.020-firmware-version (flash_ng) does not work correctly. You can't edit the ID... Close when fixed.

**Comment by aeickho** [comment]
Tnx kim,
   I can confirm this bug. I'll check my hooks tomorrow. Hopefully it is only a typo and not an big change in the fw numerical edit dialogue. 
If I change a preset value (Rx frequency) the disability is different, I think there is a important variable not initialised.

- alex

Am 24. August 2016 22:28:25 MESZ, schrieb Kim - DG9VH <notifications@github.com>:
