### ISSUE TITLE
D13.020 - promiscuous-mode does not work

### ISSUE THREAD

**Issue by dg9vh** [travisgoodspeed/md380tools#222]
You can enable and disable promiscuous mode, but it does not enable it - it is not receiving TGs which are not in the RX-list.

I found it while talking to TG26208 on BM and not receiving me on my Tytera. 

Maybe typo again or wrong address?

Close when fixed.

**Comment by aeickho** [comment]
:-(

**Comment by aeickho** [comment]
I understand now, why it's not working....

**Comment by dg9vh** [comment]
That's fine.

**Comment by aeickho** [comment]
Hy Kim @dg9vh 
   can you please repeat the test

alex

**Comment by dg9vh** [comment]
@aiecko i'll do it this evening.

**Comment by dg9vh** [comment]
@aeickho tested and approved... it's working now (tested with unlisted Talkgroup, not testet with private call).

**Comment by aeickho** [comment]
private call tested be me

**Comment by dg9vh** [comment]
also tested with private call to not own ID, working also... closed
