### ISSUE TITLE
SPI Flash ID: 70 f1 1

### ISSUE THREAD

**Issue by yoony64** [travisgoodspeed/md380tools#228]
Hi,

My MD-380 has a SPI Flash ID of 70 f1 1 and it won't flash the users.csv.  This radio had the D013.020 firmware(patched).

Help!

Thank you.

**Comment by travisgoodspeed** [comment]
On what operating system are you trying to flash it?  We have a known issue that it doesn't work in MINGW, issue #186.

**Comment by yoony64** [comment]
I've been using Windows 7 64 bit.

**Comment by travisgoodspeed** [comment]
Then see issue #186, which probably describes what you're seeing.

Closing this issue as a duplicate.

**Comment by yoony64** [comment]
My radio was originally a V13.20 firmware, before modifying.  I mistakenly used a V2.32 based patch firmware and everything seems to work, but the users.csv won't work.  

With this wrong firmware, the make flashdb thinks the SPI is 10 dc 1.

Once I corrected the firmware to the patched 13.20 version, now the SPI ID says 70 f1 1 and make flashdb fails with unknown ID.
