### ISSUE TITLE
New date formats

### ISSUE THREAD

**Issue by NicoVarg99** [travisgoodspeed/md380tools#230]
A easy feature to add could be a new date format.
So you can choose between
American (MM/DD/YYYY)
German (DD.MM.YYYY)
European (DD/MM/YYYY)
Swedish (YYYY/MM/DD)

**Comment by aeickho** [comment]
@NicoVarg99 have fun and program this feature. 

This is an good starting point to work on this nice project. 

have fun,
 alex

**Comment by NicoVarg99** [comment]
Done :)

Nicola IN3GJH
