### ISSUE TITLE
TYT MD-390 no GPS D13.020 - Windows - mirorred and flipped display ...

### ISSUE THREAD

**Issue by Conrad007** [travisgoodspeed/md380tools#237]
Hello,
I have flashed the experimental firmware v1 and later also v2 (from 22.April) using the original upgrade tool, but after that I just get a horizontal flipped and mirrored welcome screen (showing my callsign and name) on white background and the device reboots into this every 20 seconds... Fortunately, I was able to bring it back to normal life by flashing again the original firmware D13.020, but I would like to have md380tools ...

**Comment by aeickho** [comment]
Yes,
   The fw from 22.april has not md380 support.

Checkout the actual sources ... And build your own experimental fw.

... Ask for support to build the fw on md380   group on Google ... See bottom of readme.md

This is not an support forum ..  ;)

73 Alex df8av

**Comment by aeickho** [comment]
#178

**Comment by Conrad007** [comment]
Ok, thanks Alex and sorry for posting in the wrong place ...
By the way, I have an **md390, new vocoder, no GPS** and I tried also the older fw (experimental) with the same results... (only for info).
Generally, should I quit trying on Windows and build my exp. fw in Linux?

73 Conrad

**Comment by Conrad007** [comment]
Solved and working! I was just using my Raspberry Pi with Debian Jessie. I'm very pleased, thanks for all you nice work!
