### ISSUE TITLE
personal development workflow documentation

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#238]
It would be nice to see some notes on the development workflow. 
- is testing possible without disconnect and reboot? (sound?)
- does it make sense to run in qemu?

**Comment by aeickho** [comment]
Hy Simon,
      My workflow...  Reading the fw with radare2 writing annotations. If I find an interesting place /  function. I write an diagnostic hook to see the calling parameters via md380tools dmsgtail .

My start point was the stm32 internals @0x40000000 ... Clock, spi, gpio ... 

This was the way to find the date format. :)

I think qemu-arm is not for all a good support. There are so many. Of tasks .. and internal communications... This is not easy to simulate. 

I like debug with printf ;)

And there is a lot of debug log space free on spi flash 

Also .. an good start point create task

73 from Goettingen, 
     Alex df8av

**Comment by aeickho** [comment]
[..]

>- is testing possible without disconnect and reboot? (sound?)

I have solder a cable .. that's allowed USB and sound

**Comment by aeickho** [comment]
if you @sijskes have no more questions please close this issue, tnx

**Comment by sijskes** [comment]
i think we should let this issue open until we have created a document from the information in this issue.
it does not have to happen today or tomorrow.

**Comment by travisgoodspeed** [comment]
Agreed.

Assigning myself, @aeickho and @cr to document our workflow.  Unassign yourself as documentation for your workflow is written.

**Comment by travisgoodspeed** [comment]
Opened #269 to track the creation of the wiki.  I'll write tutorials for opening the firmware in IDA Pro and Radare2 when I get a chance.
