### ISSUE TITLE
Issue with 1750 Hz Tone button assignment @ fw XY3.020

### ISSUE THREAD

**Issue by HB9TQJ** [travisgoodspeed/md380tools#253]
I noticed one bug: If I assign 1750 Hz Tone to one button the secondary function (long or short press) does not work.

**Comment by claywalker0929** [comment]
Is this really a bug? My understanding is the 1750 hz tone is to operate certain circuits. It would seem the desired function would be for the tone to last as long as the button is held.

**Comment by der-stefan** [comment]
I think this issue is solved with #652 
At least the 1750 Hz tone works fine with my RT3.
