### ISSUE TITLE
New flashing icon on my MD-390 with latest e800 firmware

### ISSUE THREAD

**Issue by iball** [travisgoodspeed/md380tools#257]
Just noticed this.  Icon next to the scan icon now flashes randomly.  This is on an MD-390 (No GPS).
Not seeing it on my MD-380 at all.
Is this normal behavior on an MD-390 now?
See screenshot for details.
![img_0059](https://cloud.githubusercontent.com/assets/1633825/18256614/4b2936a4-737d-11e6-8dc0-f0496d54d06d.JPG)

**Comment by sijskes** [comment]
flashing 'eye' icons indicates promiscuous mode active.

**Comment by iball** [comment]
That's weird because I've never turned it on before on either radio.  
Just found it was turned on by default with the new e800 commit of the code?

**Comment by sijskes** [comment]
probably garbage in spi flash, clipped to 1 value = on.

**Comment by travisgoodspeed** [comment]
Closing this issue.  Re-open as a new issue if we need to add a checksum to the menu configuration to make it more predictable.
