### ISSUE TITLE
proposal for firmware defines

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#270]
To conditional include code i propose:

#define FW_D13_020  1

to be passed when compiling for d13.020 fw. etc....

**Comment by travisgoodspeed** [comment]
Welcome to the team, neighbor!

Approved.  Close this issue when each version has its definition.

**Comment by sijskes** [comment]
Thanks for inviting me.

Created a wiki page with the defines 'Coding Notes'. 

Will close when it is in makefile

**Comment by aeickho** [comment]
I prefer "my" style.. it's the same as the folder structure and there is only one change in the makefile necessary.

See on makefile ....

**Comment by aeickho** [comment]
See also my comments #272 ;-)

**Comment by roelandjansen** [comment]
I believe that sijske's idea is a good thing.

**Comment by aeickho** [comment]
see:
https://github.com/travisgoodspeed/md380tools/blob/master/applet/Makefile#L38
and:
https://github.com/travisgoodspeed/md380tools/blob/master/applet/src/beep_process.c

**Comment by sijskes** [comment]
roger. did not see that as firmware specific. more hardware specific. when you mention MD380 in a define, this can happen.

**Comment by aeickho** [comment]
@sijskes  Is your define to "1" important for your concept?

my idea ...
CFLAGS += -D "MD380_$(subst s,S,$(subst d,D,$(subst .,_,$(SRCVERSION))))"
then the new "based on fw define" is:

**MD380_D13_020**

**Comment by sijskes** [comment]
implemented proposal
