### ISSUE TITLE
Add warning for not implemented functions on other platforms

### ISSUE THREAD

**Issue by aeickho** [travisgoodspeed/md380tools#274]
To syncing the different platforms I think it's necessary that we have an mechanism to see what is new. And my proposal: compile warning ... Or an new issue. 

...
Btw: I have ordered an gps type radio... Then I can test my work... In this time... It's only cold coding and verifying with radare2

**Comment by sijskes** [comment]
a coder always has a diff at his disposal. best tool there is. i'm not going to put in the effort to create release notes.

**Comment by sijskes** [comment]
let's take it step bij step. no BDUF on coding and project layout please.

**Comment by sijskes** [comment]
done
