### ISSUE TITLE
Full screen RX popup ... Antenna, Battery and transmit power indicators 

### ISSUE THREAD

**Issue by PD1WP** [travisgoodspeed/md380tools#309]
Future wish:  Is it possible to create at the top of the screen the battery, H or L transmit power and the antenna indicators?  When it gets very busy on a channel, is this information is no longer visible. Sorry for my bad English.  PD1WP 2046132  Wilfred

**Comment by aeickho** [comment]
@hsmade  can you fix it please.....

**Comment by hsmade** [comment]
I did already, I offered the commit to @sijskes: https://github.com/hsmade/md380tools/commit/270f8d72db1de4002001a7ab5d2b75044a498e96

**Comment by sijskes** [comment]
@hsmade can you do a pull request?

**Comment by hsmade** [comment]
https://github.com/travisgoodspeed/md380tools/pull/310
