### ISSUE TITLE
RX screen Text slightly larger.

### ISSUE THREAD

**Issue by PD1LOI** [travisgoodspeed/md380tools#319]
It is not a problem, but a question.
Is it possible the text ID and Country and City in the RX screen to make something bigger like 2 dots bigger Call name is Correct.
73.

**Comment by maushammer** [comment]
The radio has only two latin fonts -- a large one (10x16) and a small one (6x12).  In my experience, resizing bitmapped fonts yields ugly results (diagonal lines get kinks) and adding a new font would require some work.

So, it's possible, but not simple.

**Comment by travisgoodspeed** [comment]
Closing this issue as too much effort. Reopen it if someone will volunteer to make a giant font for callsigns and to implement a function for drawing that text.
