### ISSUE TITLE
create permanent display of last used talkgroup

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#350]
As reported by: PD1RHV

When running in promisc mode, in combination with the dvmega, it helps when the last used talkgroup is permanent on the display. (aids in controling the dvmega).

**Comment by sijskes** [comment]
fixed in: https://github.com/travisgoodspeed/md380tools/pull/415

**Comment by m0ivq** [comment]
What does the '28' mean to the right of the talkgroup number?

![wp_20161002_13_15_51_pro](https://cloud.githubusercontent.com/assets/15026735/19020515/bb221aae-88a2-11e6-940d-1da232b3b903.jpg)

**Comment by sijskes** [comment]
debug artifact.
