### ISSUE TITLE
Squelch works not anymore

### ISSUE THREAD

**Issue by PD1WP** [travisgoodspeed/md380tools#365]
I updated my Tytera md-390 to the latest version with Ubuntu And from that moment the Squelch does not work anymore on my analog channels. I also tried the version from PD0ZRY with the same results.  Now i have downloaded  the latest version of yesterday from the site from  PD0ZRY and the Squelch works perfectly.

**Comment by roelandjansen** [comment]
We also noticed wit the latest build we did. The version that works OK and still with most of the 
netmon features is here https://github.com/roelandjansen/md380tools/releases/tag/b0ba798 
and these builds are built directly after a merge has taken place.

**Comment by sijskes** [comment]
@PD1WP thanks for your report. i didnt notice it during testing, too much focused on the dmr radio layer.

You can indeed find stable releases on the roelandjansen releases page. 

But i like people testing the 'unstable' releases as well. :)

**Comment by roelandjansen** [comment]
I do too.

https://github.com/roelandjansen/md380tools/releases

is the place where all our builds are stored./ Older builds willl be deleted after some time. Also Once in a while we'll pick a stable release and publish it on the ham-dmr/hamdigitaal website

**Comment by roelandjansen** [comment]
see

https://github.com/roelandjansen/md380tools/releases/tag/e8c3e56

with a working SQ.
