### ISSUE TITLE
integration of version specific makefiles

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#386]
approach: 
create an include file where all shared stuff will be consolidated.
when consoldation is progressed and 3 versions are working, considering creating 1 Makefile with conditionals.

any info if this will work for windows and mac platform? do they all run GNU make?

**Comment by travisgoodspeed** [comment]
Windows does run GNU Make, but often there is a space in `make`'s path just to mess with you.  BSD runs BSD make, of course, but has `gmake` as a separate command.

Let's first push a draft of the new Makefile, then quickly have some Windows folks try it and adjust the documentation before making it the default.

**Comment by sijskes** [comment]
made mods on applet/Makefile. saved original for quick revert.
validated D02 build by flashing and using.

**Comment by sijskes** [comment]
are there any issues detected?

**Comment by travisgoodspeed** [comment]
Works fine on Mac, but we don't yet have confirmation for GNUWin32 or Cygwin.  (Windows Services for Linux should be fine.)

Is anyone using BSD for this project?

**Comment by m0ivq** [comment]
I'll check on GNUWin32 & Cygwin tomorrow.

**Comment by m0ivq** [comment]
Works ok under GNUWin32, not yet tested on Cygwin.

**Comment by travisgoodspeed** [comment]
I think this is responsible for 'make dist' being broken in GNU Make 3.81 on OS X.  GNU Make 4.1 on the same platform works without trouble.

Fix before closing the issue:
- [ ] GNU Make 3.81 on OS X

**Comment by sijskes** [comment]
@travisgoodspeed do you have more info? is there a build environ where i can see the errors myself?

**Comment by m0ivq** [comment]
I didn't test properly under Windows! 'make dist' gives the following error:

`C:/Progra~1/GnuWin32/bin/make -C applet --eval=FW=D13_020 all`
`C:/Progra~1/GnuWin32/bin/make: unrecognized option ```--eval=FW=D13_020'`

**Comment by travisgoodspeed** [comment]
GNU Make 3.81 is the version shipped with XCode, so any Mac will work as a build environment.

@m0ivq I see the same error that you do.

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C applet --eval=FW=D13_020 all  
/Applications/Xcode.app/Contents/Developer/usr/bin/make: unrecognized option `--eval=FW=D13_020'
```

**Comment by sijskes** [comment]
@travisgoodspeed i have it converted to -D if P1 is merged please test again.

**Comment by sijskes** [comment]
please test after merge. i've removed the --eval from P1

**Comment by sijskes** [comment]
@travisgoodspeed i've done the merge. went back to old style defines. could you test again?

**Comment by travisgoodspeed** [comment]
I'll be able to test in an hour or so.  @m0ivq might be able to test sooner, as he can reproduce the same issue.

**Comment by m0ivq** [comment]
@sijskes now works on Windows (make 3.81) though I need to update the Windows Instructions to install 'zip.exe'

Make 4.1 under windows has other issues but may be down to my installation.

**Comment by sijskes** [comment]
@m0ivq make4.1 windows, what kind?

**Comment by m0ivq** [comment]
@sijskes I get the following but haven't had time to look into it yet:

`C:/Progra~1/GnuWin32/bin/make -C lib
make[2]: Entering directory 'C:/Users/post2/Desktop/git/travisgoodspeed/md380tools/applet/lib'
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o misc.o src/peripherals/misc.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_dma.o src/peripherals/stm32f4xx_dma.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_rcc.o src/peripherals/stm32f4xx_rcc.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_adc.o src/peripherals/stm32f4xx_adc.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_exti.o src/peripherals/stm32f4xx_exti.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_rng.o src/peripherals/stm32f4xx_rng.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_can.o src/peripherals/stm32f4xx_can.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_flash.o src/peripherals/stm32f4xx_flash.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_rtc.o src/peripherals/stm32f4xx_rtc.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_crc.o src/peripherals/stm32f4xx_crc.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_fsmc.o src/peripherals/stm32f4xx_fsmc.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_sdio.o src/peripherals/stm32f4xx_sdio.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_cryp_aes.o src/peripherals/stm32f4xx_cryp_aes.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_gpio.o src/peripherals/stm32f4xx_gpio.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_spi.o src/peripherals/stm32f4xx_spi.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_cryp.o src/peripherals/stm32f4xx_cryp.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_hash.o src/peripherals/stm32f4xx_hash.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_syscfg.o src/peripherals/stm32f4xx_syscfg.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_cryp_des.o src/peripherals/stm32f4xx_cryp_des.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_hash_md5.o src/peripherals/stm32f4xx_hash_md5.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_tim.o src/peripherals/stm32f4xx_tim.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_cryp_tdes.o src/peripherals/stm32f4xx_cryp_tdes.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_hash_sha1.o src/peripherals/stm32f4xx_hash_sha1.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_usart.o src/peripherals/stm32f4xx_usart.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_dac.o src/peripherals/stm32f4xx_dac.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_i2c.o src/peripherals/stm32f4xx_i2c.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_wwdg.o src/peripherals/stm32f4xx_wwdg.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_dbgmcu.o src/peripherals/stm32f4xx_dbgmcu.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_iwdg.o src/peripherals/stm32f4xx_iwdg.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_dcmi.o src/peripherals/stm32f4xx_dcmi.c
arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core -Iinc/peripherals -fshort-wchar -c -o stm32f4xx_pwr.o src/peripherals/stm32f4xx_pwr.c
arm-none-eabi-ar -r libstm32f4.a misc.o stm32f4xx_dma.o stm32f4xx_rcc.o stm32f4xx_adc.o stm32f4xx_exti.o stm32f4xx_rng.o stm32f4xx_can.o stm32f4xx_flash.o stm32f4xx_rtc.o stm32f4xx_crc.o stm32f4xx_fsmc.o stm32f4xx_sdio.o stm32f4xx_cryp_aes.o stm32f4xx_gpio.o stm32f4xx_spi.o stm32f4xx_cryp.o stm32f4xx_hash.o stm32f4xx_syscfg.o stm32f4xx_cryp_des.o stm32f4xx_hash_md5.o stm32f4xx_tim.o stm32f4xx_cryp_tdes.o stm32f4xx_hash_sha1.o stm32f4xx_usart.o stm32f4xx_dac.o stm32f4xx_i2c.o stm32f4xx_wwdg.o stm32f4xx_dbgmcu.o stm32f4xx_iwdg.o stm32f4xx_dcmi.o stm32f4xx_pwr.o
arm-none-eabi-ar: creating libstm32f4.a
make[2]: Leaving directory 'C:/Users/post2/Desktop/git/travisgoodspeed/md380tools/applet/lib'
g++    -c -o main.o src/main.c
process_begin: CreateProcess(NULL, g++ -c -o main.o src/main.c, ...) failed.
make (e=2): The system cannot find the file specified.
<builtin>: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 2
make[1]: Leaving directory 'C:/Users/post2/Desktop/git/travisgoodspeed/md380tools/applet'
makefile:22: recipe for target 'applets' failed
make: *** [applets] Error 2`

**Comment by sijskes** [comment]
@m0ivq is looks like it tries to start the stock g++ compiler. but stranger still why does it compile main.o with the g++ compiler? is the main.c actually main.C ?

**Comment by travisgoodspeed** [comment]
@sijskes Confirmed that the fix works for GNU Make 3.81 on OS X.

**Comment by sijskes** [comment]
@m0ivq we can try by overriding the .C rule with the same as .c

**Comment by sijskes** [comment]
implemented
