### ISSUE TITLE
Netmon optie 2 block everything.

### ISSUE THREAD

**Issue by PD1LOI** [travisgoodspeed/md380tools#394]
Netmon option 2 blocks from the menu. in the latest version

**Comment by roelandjansen** [comment]
What is the "latest" version and more, realise it is for debugging.

**Comment by PD1LOI** [comment]
Last version is 27-09-2016 12.00 uur

Op 27 sep. 2016 19:42 schreef "Roeland Jansen" <notifications@github.com>:

**Comment by roelandjansen** [comment]
https://github.com/roelandjansen/md380tools/releases/tag/e08b733 is the latest build. It is a prerelease.

**Comment by sijskes** [comment]
It is not advised to use the netmonitor if you are not a developer. 
The user experience will be not as expected, and only make sense when you read the sourcecode of the same release that you are using.

**Comment by sijskes** [comment]
Not an error.
