### ISSUE TITLE
md380-tool calllog

### ISSUE THREAD

**Issue by ispkorte** [travisgoodspeed/md380tools#395]
if i start **md380-tool calllog** and at the moment a call come in , radio will hangout
see at picture screen after 2 min make off radio (its not OFF , it is ON)

![img_20160928_100512](https://cloud.githubusercontent.com/assets/22329165/18905592/388bd24c-8564-11e6-95b0-707940d02296.jpg)

**Comment by sijskes** [comment]
Can you tell us more? Which version? Does it still occur with the latest? Could you try the stable release @ https://github.com/roelandjansen/md380tools/releases/tag/66d3e86

**Comment by ispkorte** [comment]
its a RT8 S13 - stable - from 2016-09-27

**Comment by sijskes** [comment]
is it reproducable? 

does it still occur with the lastest version: https://github.com/roelandjansen/md380tools/releases/tag/e08b733

**Comment by sijskes** [comment]
So to be clear, the volume knob was turned in the off position?

**Comment by ispkorte** [comment]
radio was fail after a call on 232 was come in , 5 min nothing doing i was make OFF but radi was not off ; after 2min i have open accu for off

**Comment by ispkorte** [comment]
i have had **md380tools-66d3e86** inside RT8 
start **./md380-tool calllog** but nothing comes 
in some times a call go in - display stop (see picture) and ratio was freez
also in the daily version from today 

i have no idea about fail at my side or not

**Comment by sijskes** [comment]
@ispkorte  i don't think it is a fail at your side. 
did the problem repeat itself any other time?

**Comment by ispkorte** [comment]
at 66d3e86 i can repeat fail ; now i have the new 0666ab8 from 1PM(UTC) and no fail
but i get no line at **./md380-tool calllog**

**Comment by sijskes** [comment]
@aeickho is calllog ever ported to D13? i see memory constants in md380-tool.

**Comment by travisgoodspeed** [comment]
The calllog tool is an ugly, ugly hack from the early days of this project.  We should make our own buffer for recent calls from our C hooks instead.

**Comment by ispkorte** [comment]
ok fellow , close for now until you have time back for restart
