### ISSUE TITLE
need snprintf and swprintf for safe printing

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#416]

**Comment by travisgoodspeed** [comment]
We actually have these functions, but as part of newlib and depending upon a heap.  As a solution, we can either (1) add a heap and potentially run out of memory or (2) extend `printf.c` with implementations of `snprintf` and `swprintf` that do not require heap memory.

To avoid worrying about memory usage for the rest of our project, I strongly suggest the latter.

**Comment by sijskes** [comment]
implementation is possilbe with tpf_print. instead of passing just the char* pointer, pass a structure with begin and end off buffer.

**Comment by sijskes** [comment]
no heap please.

**Comment by sijskes** [comment]
implemented
