### ISSUE TITLE
Mic bar on received on a18d5b8-dirty

### ISSUE THREAD

**Issue by ispkorte** [travisgoodspeed/md380tools#428]
if you send and mic bar is on it will place in received mode also some time and you cant see user info
is it a bug or not ?

![whatsapp image 2016-10-04 at 07 13 49](https://cloud.githubusercontent.com/assets/22329165/19063349/38baacfa-8a02-11e6-949e-62397efbb504.jpeg)
![whatsapp image 2016-10-04 at 07 13 49 1](https://cloud.githubusercontent.com/assets/22329165/19063350/38c211e8-8a02-11e6-9276-8e2027d3f25e.jpeg)

**Comment by sijskes** [comment]
Yes, i can confirm this as a bug.

**Comment by ispkorte** [comment]
i flash **d9c1676-dirty** and i check bug again but nothing found . i thing it was fix , right ?

**Comment by sijskes** [comment]
@ispkorte no, it is not fixed. it is timing-dependend. sometimes the erasure of the micbar just arrives too late. or the end of tx popup too early.

**Comment by ispkorte** [comment]
OK thanks
