### ISSUE TITLE
something wrong with travis-ci?

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#435]
See: #434  clang compiler

i can see this relating to the commits.

**Comment by sijskes** [comment]
$ if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then sudo ln -s /usr/bin/python /usr/bin/python2; fi
ln: /usr/bin/python2: Operation not permitted


The command "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then sudo ln -s /usr/bin/python /usr/bin/python2; fi" failed and exited with 1 during .

Your build has been stopped.
/Users/travis/build.sh: line 109: shell_session_update: command not found

**Comment by sijskes** [comment]
i merged, and now the relation with the build is gone. it was in the early setup of the container calling several 'brew'.

**Comment by sijskes** [comment]
strange thing. the ln is run with sudo. maybe /usr/bin/ is read only mounted fs?

**Comment by travisgoodspeed** [comment]
Perhaps travis-ci should be running `make dist` rather than `make install`?

**Comment by sijskes** [comment]
@travisgoodspeed  better. but it looks likes it goes wrong in preparing the container. i will change to make ci

**Comment by sijskes** [comment]
setup of clang part is broken before make ci is called.

**Comment by travisgoodspeed** [comment]
Does Travis CI build in an OS X VM?  I assumed they'd use Docker with a Linux VM.

`/usr/bin` isn't writable on modern OS X, even as root, so I'd expect that line to fail.  `/usr/local/bin/` is writable and in the default `$PATH`.

**Comment by d235j** [comment]
They may have upgraded to 10.12 which introduced Rootless.
The reason for that line was to work around the python2 -> python problem. Seems we need a better solution.

**Comment by travisgoodspeed** [comment]
Status screen is at https://travis-ci.org/travisgoodspeed/md380tools

Self-assigning.  I'll have this passing today.

**Comment by travisgoodspeed** [comment]
Hey, that worked on the first try!  Closing issue.
