### ISSUE TITLE
which task does the I2C IC U307

### ISSUE THREAD

**Issue by aeickho** [travisgoodspeed/md380tools#44]
next week, i'll look on the calling functions .. to see with task is involved 
and i'll look to find the I2C address   

 on https://github.com/travisgoodspeed/md380tools/issues/40 
-->
  Software Control Watch Dog Serial Clock
  Software Control Watch Dog Serial Data

```

**Comment by aeickho** [comment]
```
af+ 0x08046a28 306 Big_I2C_Function()   
af+ 0x0804ff74 244 Function_Called_Big_I2C_Function()
af+ 0x08050068 270 Function_Function_Called_Big_I2C_Function()
af+ 0x08046e00 156 Function_Function_Function_Called_Big_I2C_Function()
af+ 0x08032a3c 146 Function_Function_Function_Function_Called_Big_I2C_Function(
CCa 0x08032a3c Called from Task Start()


```

**Comment by tristantech** [comment]
I became curious about this too. It has something to do with the vocoder. The IC is called the HR_V3000S according to the schematic. There is very little information out there about it, sadly. I found lots of [other Chinese DMR radios](http://fjlisheng.en.alibaba.com/product/60182522239-221438579/DMR_Tier_2_Mototrbo_System_DM_R77_DMR_System.html) mentioning use of the  "DVIS HRV3000" as the vocoder. I presume "DVIS" is a knock-off of DVSI, which makes the real AMBE vocoders. "HR" is the same prefix as the DMR processor IC. It would not surprise me that China has reverse engineered or implemented the AMBE+ spec. However, to say that this 6-pin package, connected soley over I2C, _is_ the vocoder may be a big stretch. Perhaps it's a hardware token/dongle to activate the actual vocoder, inside the STM32?

Tapping the I2C bus would provide some valuable information. There is also a pack of code called "HR_V3000-vocoder-use" floating around on a bunch of sketchy Chinese download sites that you can find through Google. They make you either pay or upload lots of stuff to get the files. I think it would be very valuable to get a look at whatever that code is.

Tristan Honscheid / KD8YHB

**Comment by aeickho** [comment]
from the dr6000 schematic ...  alpu-mp -> 
http://wenku.baidu.com/view/cb189e29dd36a32d737581aa.html?re=view
http://www.xcjy876.com/html/98y56bz6aa0370za40425y77.html

**Comment by kb9mwr** [comment]
How to download from wenku.baidu: http://pastebin.com/ynJ9kLdU

Else: http://www.qsl.net/kb9mwr/projects/dv/dmr/ALPU-MP_datasheet_v2.16.pdf

**Comment by aeickho** [comment]
Tnx

Am 13. Juni 2016 03:24:44 MESZ, schrieb kb9mwr <notifications@github.com>:

**Comment by aeickho** [comment]
now on #168
