### ISSUE TITLE
refactor config storage proposal

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#442]
make 1 call for save and 1 for load from spi flash of a single structure.
remove all the spi_read calls in menu generation.

**Comment by aeickho** [comment]
dear @sijskes 
  yes... do it ..  :smile:

I'm temporary very busy. :( 

config wish list...:
- flags
- ints
- strings  (Call sign) 
 (for generic codeplug usage ) .. Welcome line[1,2], dmr-id will be overwritten by our config

**Comment by sijskes** [comment]
implemented
