### ISSUE TITLE
MD390 / RT8 volume knob 

### ISSUE THREAD

**Issue by ispkorte** [travisgoodspeed/md380tools#446]
I wonder about two radio units RT8, if I be located with my RT8 the volume knob counter clockwise to 0% then I hear still talks. 

(i don't know about a bug on hardware or a fault in firmware) is there anybody to confirm it  ?

**Comment by hamradioPRC** [comment]
This is a known issue with stock firmware. Tytera and clones won't do anything to fix it am afraid. Good idea for the hackers

**Comment by hamradioPRC** [comment]
This will be closed when a fix is understood

**Comment by m0ivq** [comment]
The volume level itself is hardware and not controlled by the firmware (unless that has changed in later models). The only connection to the micro is to measure the position of the volume control in order to display the volume setting.

**Comment by eb4fbz** [comment]
There is a resistor in series with the volume pot to ensure a minimum volume with pot at 0%, it's done on purpose so you don't miss any transmission by mistake.

**Comment by ispkorte** [comment]
ok ; it is a feature , not a bug 
thanks eb4fbz
(dd1go/hs0zkj)

**Comment by eb4fbz** [comment]
This is the resistor, just in case someone wants to eliminate that feature. Just bridge it  or the potentiometer pin to ground.
![rt9_min_vol_resistor](https://cloud.githubusercontent.com/assets/20281008/19215049/3f55b96c-8d93-11e6-905a-290fd0bd4ab5.png)

**Comment by ispkorte** [comment]
many tnx to eb4fbx

i check it

**Comment by sijskes** [comment]
hardware issue. closing.
