### ISSUE TITLE
firmware makefile problem

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#453]
with make 3.61 it doesnt work conform makefile semantics.

when a target is made, and previous only a clean has been run, the wrong intermediate target is selected. 

workaround, always do a download in a separate make before calling for a real target.

test_ok.sh
test_fail.sh 
are included, and verified in the ci build containers

**Comment by ispkorte** [comment]
i get error ,too


60df702..91b3155
error: Your local changes to the following files would be overwritten by merge:
        patches/2.032/Makefile
Please, commit your changes or stash them before you can merge.
Aborting
(on Mint17.3)

**Comment by phl0** [comment]
You made local changes to the Makefile. That prevents an update. You may want to revert the changes before updating / merging.

**Comment by ispkorte** [comment]
i have definitely nothing change ; yesterday it works fine , shutdown and today restart , pull take a fault 

my last working get 60df702

**Comment by phl0** [comment]
What is the output of "git diff"?

**Comment by sijskes** [comment]
please open a new issue, this is completely unrelated to the issue at hand.

**Comment by travisgoodspeed** [comment]
Is this still a problem?  I've checked all of my servers, but even that OpenBSD machine that I physically lost but can reach by the network is running gmake 3.81.  (Or perhaps I misunderstand how to reproduce the issue.  Maybe a shell log would help?)

**Comment by sijskes** [comment]
@travisgoodspeed problem is still there but worked around with dual step makefile trickery. closing.
