### ISSUE TITLE
provide instructions for cygwin users to create proper pathnames

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#486]
with spaces escaped.

**Comment by travisgoodspeed** [comment]
With my recent patches, escaped pathnames should no longer be required.

(Can we add an appropriate emoji to the Windows label?  Maybe a thumbs-down or poop?)

**Comment by sijskes** [comment]
i like it more when the quotes go, and a fix for the path with cygpath in the top of the makefile.
