### ISSUE TITLE
16 digit Contact Name display garbled on TX

### ISSUE THREAD

**Issue by jruys** [travisgoodspeed/md380tools#488]
When a Private Call Contact Name has maximum length (16 characters), bottom line of TX display is garbled: it shows a mix of the Contact and Zone.

Display is fine with shorter Contact Names and with Group Calls.

Can provide pictures if required.

**Comment by roelandjansen** [comment]
please do. It's unclear if you are referring to the normal userid or with the users.csv option.
Also, what version do you use.

**Comment by jruys** [comment]
Version is 3ffa38f (I cloned it 14/10/2016) - and referring to normal userid via the code plug.

This is transmitting with contact name "5000 Status"", all is well:

![image](https://cloud.githubusercontent.com/assets/16433735/19398797/a4744060-924e-11e6-80fa-743e4632f881.png)

This is transmitting with contact name "Echo 9990 123456", note how the "9990"disappeared, and "MMDVM" appeared at the end (the zone is called "MMDVM"):

![image](https://cloud.githubusercontent.com/assets/16433735/19398806/b1094672-924e-11e6-82ae-fd88b4596c30.png)

**Comment by hamradioPRC** [comment]
MMDVM= 'Multimode Digital Voice Media'

**Comment by travisgoodspeed** [comment]
This is a string termination bug in the original firmware. I'm tempted to close as "won't fix."

**Comment by jruys** [comment]
Could have sworn it wasn't there in the early days of MD380 patched firmware but no problem to close - I've changed codeplug to 15 characters maximum now.

**Comment by travisgoodspeed** [comment]
Closing as "won't fix."  If you encounter this bug, please do as @jruys suggests and workaround by limiting your contact names to 15 characters.
