### ISSUE TITLE
400-480 to 136-174 conversion

### ISSUE THREAD

**Issue by bilbolodz** [travisgoodspeed/md380tools#49]
Does anyone know is it possible to reprogram band in radio? Is it firmware or hardware issue?

**Comment by smiffys** [comment]
Its hardware you cannot change the band with firmware

**Comment by bilbolodz** [comment]
Thanks

**Comment by bilbolodz** [comment]
How about firmware? Is it "universal" (UHF/VHF)? I would like to buy 136-174 version but also I want to have chance to load moded firmware a play with these new firmware.

**Comment by ajorg** [comment]
It's hardware.

**Comment by cr** [comment]
The UHF and VHF hardware uses identical firmware in the MD380. I would expect it to just work, but be advised that we have no feedback that it actually does, yet.

**Comment by smiffys** [comment]
It does work fine, I have patched 2.032 firmware in my Retevis RT3 VHF and UHF radios

**Comment by travisgoodspeed** [comment]
I'm also using it on the VHF model with no problems. Closing issue.

**Comment by ajorg** [comment]
Oh, I get it. Sorry for chiming in without understanding first.
