### ISSUE TITLE
Firmware where only the user.csv can be used?

### ISSUE THREAD

**Issue by PD1LOI** [travisgoodspeed/md380tools#490]
No error message but a request.
Is it possible to create a firmware where only the user.csv can be used, and further just standard just as the original?
At the request of a few amateurs.
greetings PD1LOI

**Comment by travisgoodspeed** [comment]
Sorry PD1LOI, but we are trying to reduce the number of different release flavors that we make, rather than to make more of them.

Can you explain why they want a release with fewer features?  Perhaps we could do something with the configuration to stop whatever problem they are having.

**Comment by PD1LOI** [comment]
Older amateurs find the option user.csv enough. they use the other options.

Op 15 okt. 2016 18:37 schreef "Travis Goodspeed" <notifications@github.com>:

**Comment by roelandjansen** [comment]
then just don't use the other options. simple as that. I also feel that too many diversions just causes headaches with the issue tracker here.

**Comment by travisgoodspeed** [comment]
Closing this issue.  Future feature requests should begin on Issue #370 rather than starting as their own issue in the tracker.
