### ISSUE TITLE
Documentation of Experimental and Debug Menus

### ISSUE THREAD

**Issue by IK8JHL** [travisgoodspeed/md380tools#495]
what are do  the expmerintal menu and debug?

**Comment by hamradioPRC** [comment]
DON'T enable debug menu as it drains battery power.

**Comment by IK8JHL** [comment]
ok thanks but what do ???? i dont find any information on the web , some people know where i can found more ?

**Comment by hamradioPRC** [comment]
From the first stable release build you would enable both promiscuous and experiment modes to have last heard talk group display on screen (bottom left corner!)

**Comment by sijskes** [comment]
https://github.com/travisgoodspeed/md380tools/wiki/Menu-options started

**Comment by sijskes** [comment]
done. ask additional question as input for wiki.

**Comment by sijskes** [comment]
leaving open, to collect response. 

before you ask extra question, please check current status of https://github.com/travisgoodspeed/md380tools/wiki/Menu-options

**Comment by IK8JHL** [comment]
Ok many thanks ,now its more clear,
Another question on the Netmon , i Enable menu' " Dev Only!!! " NeMon1" 2 end 3 buto i dont understand how works the Hot Keys , i have try but dont change nothings

**Comment by sijskes** [comment]
you have to have a little patience here. the document and latest release are not yet in sync.

**Comment by sijskes** [comment]
docs should be in sync with head.
