### ISSUE TITLE
compile warnings

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#526]
src/menu.c:546:5: warning: implicit declaration of function 'set_radio_name' [-Wimplicit-function-declaration]
     set_radio_name();
     ^
src/menu.c: At top level:
src/menu.c:879:6: warning: conflicting types for 'set_radio_name'
 void set_radio_name()
      ^
src/menu.c:546:5: note: previous implicit declaration of 'set_radio_name' was here
     set_radio_name();

**Comment by xSmurf** [comment]
My bad, can you assign this to me? I'll fix it shortly.

**Comment by sijskes** [comment]
consider it assigned.
