### ISSUE TITLE
Display issue with md380tools backlight menu

### ISSUE THREAD

**Issue by xSmurf** [travisgoodspeed/md380tools#528]
On saving, the redrawing gets messed up. This is because the wrong menu type is used as per https://github.com/travisgoodspeed/md380tools/commit/cc37da36f28cbc5d858d9deb4c0acc93466003f3#diff-9750c96407ee9f6d4e19ac7861ea8484R921

![backlight_menu_prob](https://cloud.githubusercontent.com/assets/525356/19629200/9396ccce-995e-11e6-89f4-85da3c53b7cb.jpg)

**Comment by sijskes** [comment]
its yours. :)

**Comment by xSmurf** [comment]
It's yours, but sure I'll fix with it with that ever next patch.

**Comment by sijskes** [comment]
its yours to fix it. not blaming you for it. its all my fault. :)

**Comment by sijskes** [comment]
implemented.
