### ISSUE TITLE
virgin codeplug for md380?

### ISSUE THREAD

**Issue by nivex** [travisgoodspeed/md380tools#56]
Do you need/want a virgin codeplug image for an MD380? There's one on a mail truck with my name on it due to arrive tomorrow. If so, let me know what command I need to run and I'll post it.

**Comment by travisgoodspeed** [comment]
Yes!  Please run `md380-dfu read md380.bin` when it arrives to acquire a virgin codeplug.

**Comment by nivex** [comment]
Alrighty! here you are:
[md380-bin.zip](https://github.com/travisgoodspeed/md380tools/files/221807/md380-bin.zip)
