### ISSUE TITLE
flashing firmware/bin/D013.020.bin causes bootloop

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#561]
if flashing firmware/bin/D013.020.bin with md380-dfu, it stays in slow reboot loop.

**Comment by travisgoodspeed** [comment]
Perhaps you have old-codec hardware, in which case D003.020 is the necessary firmware?

**Comment by aeickho** [comment]
What Type of Radio you are flashing? 

MD3[89]0-{no gps,with gps}-{new vocoder alpu, old vocoder alpu}

Alex

**Comment by sijskes** [comment]
D03 works. any pointers how to determine radiotype? sub-md380 that is?

**Comment by aeickho** [comment]
Then it is a Radio with old vocoder alpu (licences chip) .. we can rewrite the licence test on [DS]13.020 .. not only disabling the check..  but no reboot if wrong or incorrect licence else flag= new vocoder.. then we can print this.

**Comment by sijskes** [comment]
@aeickho no probl. it was about flashing original.

**Comment by travisgoodspeed** [comment]
There's no way to tell from the Recovery bootloader without starting our patched firmware. Instead of "make flashorig" you'll need to run something like "make flashorig d003.020" to specify the version. 

Closing this issue now that the mystery is solved.

-Travis
