### ISSUE TITLE
promiscuous mode switchable

### ISSUE THREAD

**Issue by aeickho** [travisgoodspeed/md380tools#58]
to new menu items for {en,dis}able 

- [x] talk groups 
- [ ] private calls

**Comment by smiffys** [comment]
Great work, any joy with promiscuous color code or timeslot yet?

**Comment by travisgoodspeed** [comment]
You can use 'md380-tool findcc` to identify the color code of a transmitter, but the C5000 chip hasn't got a setting for color code or timeslot promiscuity that I can find.

Now that @aeickho is doing extra menu items, it shouldn't be hard to move the color code finder into firmware and away from the host.

**Comment by aeickho** [comment]
I'll try to write to the screen  continuously ...

**Comment by travisgoodspeed** [comment]
Promiscuous mode is now done in C rather than assembler, and it is separately configurable for Talkgroups and Private Calls.  I've only added a menu item for TG promiscuity, but adding a Private option ought to be straightforward.

**Comment by dysinger** [comment]
I was just thinking that I wanted this feature last night.  I woke up & merged it to my master.  Didn't even have to file an issue. :D Thanks!

**Comment by rct** [comment]
FWIW, I created issue #61 to attempt to define and track a definition of basic DMR sniffing functionality that would be useful to a user in the field (without an attached computer).

Note: In addition to being able to hear what is being transmitted, it would be helpful if the user was able to determine what color code and time slot/talkgroup pair was being used.

**Comment by travisgoodspeed** [comment]
Closing this without separating the menu items.
