### ISSUE TITLE
Database update [info, no problem]

### ISSUE THREAD

**Issue by paulomartinspt** [travisgoodspeed/md380tools#581]
Received this today:

Info for all MD-380/390 and RT-3/8 users:
the database at http://dmr-marc.net/cgi-bin/trbo-database/ is updated. (**last version b4 was from (abt.) 17th of october**) ... So it´s a good reason to update the user.csv at our DMR handheld :)

vy73
Dietmar, DL4HAO

**Comment by sijskes** [comment]
reposted to googlegroups.
