### ISSUE TITLE
Dev Only key 4

### ISSUE THREAD

**Issue by IK8JHL** [travisgoodspeed/md380tools#586]
When i enable Dev Only on my MD380 and i press  key 4  , the radio goes into tx for a few seconds.
In analog mode, the radio remains locked in tx with very few milliwatts not until I turn off the radio to restore it

**Comment by ispkorte** [comment]
not on RT8 confirm

**Comment by sijskes** [comment]
pressing 4 in FM on md380 locks up controls. but does not transmit.

**Comment by IK8JHL** [comment]
Sorry i write "lock in tx " but really Led stay RED and i can wiev a very low signal on Spectrum Analyzer, in digital mode why Transmit ? do some check ?

**Comment by sijskes** [comment]
sending an sms to all other md380 users on the same repeater.
