### ISSUE TITLE
Menu operations should take precedence over receiving.

### ISSUE THREAD

**Issue by rct** [travisgoodspeed/md380tools#60]
Using the stock firmware, the menu functions aren't accessible while the radio is receiving. Menu operations will be aborted if the radio starts to receive while in the menus. It should be possible to enter the menus and change settings while on a busy channel.

Close this when it is possible to change zones while receiving.

Ideally menu operations should possible while receiving a signal and decoding audio. However, it would be preferable if it was possible to activate the menus and abort the receive operation allowing the user to regain control over the radio.

(No idea if this is remotely feasible to fix via patching, but felt it would be helpful to have this on the list of issues for replacement firmware and or patching if possible.)

**Comment by rct** [comment]
Note: some users consider this to be one of the radios top usability issues.  This should get the enhancement label.

**Comment by travisgoodspeed** [comment]
This is a big issue, particularly when trying to send a short text during a busy conversation.

**Comment by aeickho** [comment]
I'm work on it, but temporary I can't locate the technology. The message is not transported  by OSMBox :( ...

**Comment by aeickho** [comment]
fixed with 352afdd83bdc341849bece388b26d4c978095186

I'm waiting for some response/ reports .. and an good config menu name

**Comment by aeickho** [comment]
the functionality to enter the menu while receiving .. I think this is the same function ..

**Comment by travisgoodspeed** [comment]
Good job!  This works perfectly, and it's incredibly useful.  Please enable it everywhere and without a configuration option. (We'll consider this a bug fix of the original firmware.)

Close this issue when the fix is enabled by default.

**Comment by aeickho** [comment]
ok, but this patch is only the first part ... I'm work on a patch to enable the menu while rx.

is now enabled by default 
https://github.com/travisgoodspeed/md380tools/commit/9f005dc3235e68108a2957f86eeded97c6c100f0

**Comment by aeickho** [comment]
not nice ... while rx and tx  @ 0x0801f044 will not be called

**Comment by aeickho** [comment]
_"(We'll consider this a bug fix of the original firmware.)"_
maybe, I think ... more a code design problem

**Comment by aeickho** [comment]
line of thought: if  (rx or  tx  aktive ) -> Status 0x11 the keyboard is configured for dtmf tones :(

**Comment by aeickho** [comment]
update: keypad tones working while rx active

**Comment by aeickho** [comment]
0x2001d26e  key code only while pressed

**Comment by aeickho** [comment]
I'm stuck here
