### ISSUE TITLE
Show more letters per row in the display. Talkgroup number will be cut off by ..

### ISSUE THREAD

**Issue by DL9SK** [travisgoodspeed/md380tools#603]
There is a problem for displaying for example the Talkgroup 26270. In the display it is written as 2627.. (two dots as the end instead of 0). I tried 26271 as talkgroup and it will been shown correctly. Also the last name of the OM it is with two dots. There is missing a "r"

![2016-11-17 22 35 32](https://cloud.githubusercontent.com/assets/23533421/20408910/cc9cc358-ad17-11e6-9cdf-45dd61b9ebda.jpg)

It seems that there is a limitation of the signs per row in the display. Is there a possibillity to enhance the number of signs to show longer Talkgroup numbers complete.

73, Ralf DL9SK

**Comment by DL9SK** [comment]
display.c :   Removing space before and after _->_ solves the problem with long TG numbers. Then it will fit into the display line.

gfx_printf_pos( RX_POPUP_X_START, y_index, "%d -> TG %d", src, dst )

Maybe it is possible to remove this in the code.  I am not familiar with Github to to this.


gfx.h : There is a definition for length max 18 characters. Is the number limited in the stock firmware?

// max strlen = 18, if larger end in ".."

If not, where I will find the maxstrlen for expanding to 20 characters

73, Ralf DL9SK

**Comment by sijskes** [comment]
It is baked in the firmware.

I've tried to enlarge the number, but it seems the interal buffer is 
limited to 19.

https://github.com/travisgoodspeed/md380tools/commit/d346969964b664c1155b6d76a49d7c94a98106c0

**Comment by DL9SK** [comment]
Thank you very much. Enlarge to 19 and delete the spaces is enough for TG number.

**Comment by DL9SK** [comment]
Please delete also the spaces before and after - > Then it will be good enough and the issue  could closed

**Comment by sijskes** [comment]
fixed in D13.

**Comment by DL9SK** [comment]
Everything now ok. Thank you very much for new code.

73, Ralf dl9SK

ISSUE CLOSED
