### ISSUE TITLE
add "chierda D200" 

### ISSUE THREAD

**Issue by ispkorte** [travisgoodspeed/md380tools#618]
today i fix a D200 
its a MD380 clone 
difference to 380: R-SMA antenna and body-style 
![img_20161125_155859](https://cloud.githubusercontent.com/assets/22329165/20629224/ad56958c-b32a-11e6-9b59-b7467e67a7ce.jpg)

**Comment by travisgoodspeed** [comment]
Nice to know, but what is the software development issue here?

**Comment by ispkorte** [comment]
sorry  Travis , for late respond. this was only a info for developers about this model .
Software is same md380/rt3 100% compatible

**Comment by travisgoodspeed** [comment]
No worries.  Do we have a wiki page that lists known compatible models?  If not, perhaps we ought to start one.

**Comment by roelandjansen** [comment]
It is on the main page and in the docs. Just add it.

**Comment by sijskes** [comment]
https://github.com/travisgoodspeed/md380tools/wiki/MD380-Radios-and-variants
