### ISSUE TITLE
Fix RX screen after removing the Privacy sensitive data users file 

### ISSUE THREAD

**Issue by PD1WP** [travisgoodspeed/md380tools#621]
After removing the privacy sensitive data from the users file database is there an empty space left on the RX screen. When will this is solved and what comes in its place. Sorry for my English..  73ers from Apeldoorn the Netherlands.  Wilfred Pontfoort PD1WP

**Comment by DL9SK** [comment]
Missing lastname and location/county is only for european users. Outside Europe everything will be displayed. 73, Ralf DL9SK

**Comment by sijskes** [comment]
@PD1WP dont ask for 'when' in a project like this. the answer is always the same "never or somewhere in the future. it depends".
