### ISSUE TITLE
spurious: 'Netmon 3 - Call log =====" appears in syslog

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#622]
spurious: 'Netmon 3 - Call log =====" appears in syslog
at the bottom of the syslog.

no real logic to find for this message.

**Comment by DL2MF** [comment]
will check this with my next PR for the netmon4 modifications, looks like using syslog instead of lastheard.

**Comment by DL2MF** [comment]
fixed this with build #8089873

**Comment by sijskes** [comment]
i presume https://github.com/travisgoodspeed/md380tools/commit/8089873f62a0dc36786c00446d16975b2df7ea77
