### ISSUE TITLE
MD390/RT8 no Radiosettings in Utilities Menu 3

### ISSUE THREAD

**Issue by ispkorte** [travisgoodspeed/md380tools#624]
[https://goo.gl/photos/iP6kxwffyxVaAEi26] https://goo.gl/photos/iP6kxwffyxVaAEi26 here is 4 Pictures

first two is Menu from RT3
last two is Menu from RT8

on RT8 i have no option to change RX or TX settings (see attach picture)
![img_20161130_073805](https://cloud.githubusercontent.com/assets/22329165/20742710/08675506-b6d2-11e6-981c-e82826e691b7.jpg)

anybody can confirm it ?

73 DD1GO

**Comment by sijskes** [comment]
i see only 1 picture.

**Comment by ispkorte** [comment]
check link on top in message


Am 30.11.2016 um 08:15 schrieb Simon IJskes:

**Comment by travisgoodspeed** [comment]
The channel editing feature is turned on and off by the codeplug in Tytera CPS.  Do your radios have different code plugs?

**Comment by ispkorte** [comment]
is the same codeplug and some days before , menu 3 was available on RT8

**Comment by ispkorte** [comment]
my codeplug -- > http://dd1go.de/RT3/Basis-CodePlug-RT3.rdt

**Comment by ispkorte** [comment]
@travisgoodspeed  ; today i put the new (from now) firmware in my RT8 and now see Menu3 is coming back ; no codeplug change , only FW1e2c243
