### ISSUE TITLE
Question to the professionals

### ISSUE THREAD

**Issue by payadme** [travisgoodspeed/md380tools#625]
Is it possible to disable this indicator???

Absolutely useless item.

![image-0-02-05-31765e88c9239834d0dbb84d4f1f858dea6567fba90454e3a89e01bec8aa58e0-v](https://cloud.githubusercontent.com/assets/24296826/20799826/7419bd98-b7f4-11e6-952a-12c68874b1db.jpg)

**Comment by travisgoodspeed** [comment]
This is an issue tracker, not a discussion forum.  Please post wish list items in #370 or have discussions on the mailing list.
