### ISSUE TITLE
Add ability to set new TG on the fly using radio keyboard

### ISSUE THREAD

**Issue by 4Z1ZV** [travisgoodspeed/md380tools#632]
# Important #

Before you file an issue, please make sure you have discussed it on the mailinglist! 

https://groups.google.com/forum/#!forum/md380tools

**Comment by 4Z1ZV** [comment]
Adding ability to define and set on the fly new TG may be one of the strongest capabilitied of the tools.
I noticed that most of the infrastructure already available in the Dev mode.

**Comment by sijskes** [comment]
how about discussing this on googlegroups? locking issue until done.
