### ISSUE TITLE
User file display

### ISSUE THREAD

**Issue by PD1LOI** [travisgoodspeed/md380tools#634]
If the user can not be seen, it is then possible to display the screen as original again? So can you see that all our users.
![img_20161211_113625](https://cloud.githubusercontent.com/assets/2943825/21079611/ed01bc5c-bf96-11e6-8635-dc6004bb4c7a.jpg)

**Comment by PD1WP** [comment]
We fully agree with the desire of the PD1LOI to adjust the RX screen like the picture. But with retention of the entire database. The current RX screen is now half empty and this will not be turned back. This could be implemented as soon as possible? Thanks for the hard work . greatings PD1WP Wilfred

**Comment by sijskes** [comment]
this is not a forum. go to the mailinglist.

**Comment by travisgoodspeed** [comment]
Hey @PD1LOI and @PD1WP,

It's really not cool for you to keep starting feature requests and conversations as Github issues.  Issues are *only* for features and bugs which are under active development.  They are not for ideas, complaints, or advice.  They are not a forum.

Each one of these issues gets added as a TODO list for the project developers, and it sucks the fun out of our project for that list--and our inboxes!--to keep filling up.  Please, *please* take stuff like this to the mailing list and stop creating Github issues.

https://groups.google.com/forum/#!forum/md380tools

73 from Philadelphia,
--Travis KK4VCZ
