### ISSUE TITLE
please rebase pull for direct push

### ISSUE THREAD

**Issue by sijskes** [travisgoodspeed/md380tools#636]
We have removed a file from the repo, and we don't want it re-commited.

So we ask of all collaborators to do a 'git pull --rebase' in order to clean their local repo as well.

**Comment by sijskes** [comment]
And thanks to Jamie from github support!

**Comment by travisgoodspeed** [comment]
One last notice: Please run `git pull --rebase` to clean up local repositories after some recent repo surgery!

**Comment by ispkorte** [comment]
how can we do it ?
`git pull --rebase` make an error 

need before
```
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
```
and then ?

**Comment by sijskes** [comment]
please be more specific about the error.

**Comment by ispkorte** [comment]
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>
