### ISSUE TITLE
lost last character on boot screen

### ISSUE THREAD

**Issue by jamesbrownfr** [travisgoodspeed/md380tools#638]
hello,

I losted the last character on the boot screen of md380
re-inject the codeplug don't change something

![img_0698](https://cloud.githubusercontent.com/assets/24568261/21184279/10982012-c20c-11e6-8ecf-2d48825fa218.JPG)
![img_0699](https://cloud.githubusercontent.com/assets/24568261/21184336/55bec65a-c20c-11e6-80bd-9a9e753e8d67.JPG)

**Comment by DG1BGS** [comment]
Flashed the Firmware today (17th of December 2016) on Retevis RT3 with D13.020. After flashing the Firmware I get "unknown unknown" on the boot screen. Rewriting the Codeplug doesn't fix the problem.

**Comment by sijskes** [comment]
did you ask for help in the group first? closing.
