### ISSUE TITLE
latest commit breaks dist build target.  Makefile refactoring incomplete

### ISSUE THREAD

**Issue by KD4Z** [travisgoodspeed/md380tools#640]
In latest commit 8 hours ago, commit fd2d412 
In the file Makefile, mostlyclean was refactored to distclean.  However not all occurrences of mostlyclean were replaced.

Build is now broken with the dist target.

make  dist

I leverage that build target to automate build of both non-gps and gps versions without flashing step in this project.  https://github.com/KD4Z/md380tools-vm

73 KD4Z

**Comment by sijskes** [comment]
does it work again?

**Comment by KD4Z** [comment]
Looks to be working again with the latest commit.  Thanks Simon!
