### ISSUE TITLE
make flashdb failing on md-390 (no gps)

### ISSUE THREAD

**Issue by ZeroChaos-** [travisgoodspeed/md380tools#647]
git revision commit 4eda6f091d1abfc8ce6bff365d9bd8ddec69de25 from today

using a debian jessie chroot which worked about a month ago (when I last tried)

root@gato:~/md380tools# make flashdb
"make" -C db stripped.csv
make[1]: Entering directory '/root/md380tools/db'
make[1]: 'stripped.csv' is up to date.
make[1]: Leaving directory '/root/md380tools/db'
wc -c < db/stripped.csv > user.bin
cat db/stripped.csv >> user.bin
./md380-tool spiflashwrite user.bin 0x100000
[Errno 32] Pipe error
Makefile:88: recipe for target 'flashdb' failed
make: *** [flashdb] Error 1
root@gato:~/md380tools#

**Comment by travisgoodspeed** [comment]
You must flash the user's database with the firmware running, not in the bootloader mode.
