### ISSUE TITLE
FlashDB Error 1

### ISSUE THREAD

**Issue by kieranlee999** [travisgoodspeed/md380tools#653]
I am using SSH to talk with my Ubuntu PC. I am trying to upload the contacts db onto my MD380 no GPS and i am getting the following issue. Not sure if it is me or not. 

`
Traceback (most recent call last):
  File "./md380-tool", line 4, in <module>
    from md380_tool import main
  File "/home/kieran/Desktop/md380tools/md380_tool.py", line 12, in <module>
    import time, sys, struct, usb.core
ImportError: No module named core
make: *** [flashdb] Error 1
`

**Comment by travisgoodspeed** [comment]
You forgot to install Python USB 1.0.  Installing it ought to fix things.

Closing issue.
