### ISSUE TITLE
/usr/bin/python2 not createable in rootless mode

### ISSUE THREAD

**Issue by deBaer** [travisgoodspeed/md380tools#671]
In the rootless mode of macOS Sierra, it is not possible to create the link from /usr/bin/python2 as described in the README. Deactivating rootless mode is strongly discouraged. You can however create /usr/local/bin/python2, but the Makefile needs /usr/bin/python2 to exist.

**Comment by gianfrancop** [comment]
I did this:

1. disable rootless
2. create the symlink
3. go back to rootless
 
(I also use no-rootless to delete unused languages and other non-conventional stuff btw)

**Comment by svaio** [comment]
Or ... 

####Fix the environment statements for  OS X > 10.10:####

If you are using OS X > 10.10, the /usr/bin filesystem is looked by the "rootless" feature. Therefore you cannot create a lnk to python2 in this directory.

What helps and also solves an error with the pyusb Library is to run brew and build your won python2.7 package:

    brew install python
    brew install libusb
    pip install pyusb

After this, `make flash` as expected.
