### ISSUE TITLE
MD-380 power cycles repeadly after installing MD380tools.

### ISSUE THREAD

**Issue by guidoco21** [travisgoodspeed/md380tools#679]
I have an MD-380 without GPS and D013.032 firmware.  I used the instructions in"Flashing-MD380Tools-using-VMware-on__-Windows-PC.pdf" and downloaded md380tools.exe and VMware-player-12.5.2-4638234.exe after following the instructions everything worked fine then I made the mistake. It was recommended to update the contact csv list every few days so I thought I'd try it again now.  The mistake was that I held the PTT and top button putting it into bootloader and loaded the contacts list.  Since then the md-380 power cycles repeatedly.  I was able to load the D013.032 firmware back on and reloaded the codeplug and all seems ok but have tried to load md380tools again and again and it keeps cycling on and off and has not worked as it did the first time I loaded it.  I have uninstalled VMware and deleted the files from the md380tools zip and unzipped to fresh files and reinstalled VMware but still no success.  Is there a way to do a factory reset or would loading firmware and codeplug essentially reset?  Help it looked great before I messed it up.

Thanks, Guy KG7MEL

**Comment by travisgoodspeed** [comment]
Loading your firmware and a codeplug ought to reset it.

Please send support requests to the mailing list or the IRC channel, but not to this issue tracker.

Closing issue.

73 from New York,
--Travis
