### ISSUE TITLE
Where is the mailing list or IRC channel?

### ISSUE THREAD

**Issue by guidoco21** [travisgoodspeed/md380tools#680]
I'm sorry but I don't know where to find the "mailing list" or "IRC channel"?

**Comment by travisgoodspeed** [comment]
Please see the Support section of our project's README file.  It contains links to both.

Closing issue.

**Comment by travisgoodspeed** [comment]
travisgoodspeed/md380tools/blob/master/README.md

**Comment by mach327** [comment]
(The wiki 'Home' page had the IRC channel, so I just added it to the README.)
