### ISSUE TITLE
Last update D13.020 today reset

### ISSUE THREAD

**Issue by PE2K** [travisgoodspeed/md380tools#688]
D13.020 update today gives me a lot of reset in normale receiving. I never had that problem. Its after the blacklight update. On the MD380 from Tytera.

**Comment by travisgoodspeed** [comment]
@PE2K Can you please describe exactly which settings are needed to reproduce the reset?

**Comment by PE2K** [comment]
The Tytera reboots / reset itsself in a normal setting.

**Comment by travisgoodspeed** [comment]
I really need a lot more detail than that to reproduce your problem on my radio.  If I can't reproduce your problem, I can't fix it.

**Comment by travisgoodspeed** [comment]
I might have fixed your problem with my fix to #687.  Please rebuild from source and let me know if the problem persists.

**Comment by PE2K** [comment]
I have update it. And testing it.

**Comment by PE2K** [comment]
Its working fine. No resets any more. 73 PE2K
