### ISSUE TITLE
Radios with small spi flash

### ISSUE THREAD

**Issue by aeickho** [travisgoodspeed/md380tools#69]
regarding also #66

The problem is also relevant for  spi_flash_addl_config.

**Comment by aeickho** [comment]
at the moment fixed with a1361860142d9569b907b5307d0c0760fa927c00

**Comment by dg9vh** [comment]
Would in this case a solution to bring a userdb into the TRX for example with a reduced set (for example only contacts from 262xxxx or something)? Or is there no space left in memory for storing any further data?

**Comment by aeickho** [comment]
see: 5dfb1afa202ddf73e0c0a4ac5faa3a5beb21148c  there is an version with the german db in code flash. Code Flash is to expensive: so i was very happy to find space in the codeplug flash.

btw. there is some possible "unused" space near the function to enter Chinese messages. "Chinese T9"

**Comment by aeickho** [comment]
see #66
