### ISSUE TITLE
Netmon Menue is not working correctly if hangtime is on "HANG"

### ISSUE THREAD

**Issue by DL9SK** [travisgoodspeed/md380tools#699]
If set at Menue Hangtime to "HANG" the selection of the 4 menu points does not work correctly. To display the contents, it is necessery to turn the channel knob. 

After setting the Menue Hangtime for a time value it works correct.

**Comment by iw9grl** [comment]
I confirm to have the same problem, where is the Hangtime menù ?
73

**Comment by DL9SK** [comment]
It is in the CPS under Menu Hang Time.

**Comment by iw9grl** [comment]
Yes I see, but probably some fix in the code is required.
