### ISSUE TITLE
Error in compiling.

### ISSUE THREAD

**Issue by IZ4FXC** [travisgoodspeed/md380tools#740]
Hi folks!
I've reconfigured a new PC with Win7, reloaded all the necessary stuff and so no but when I try to compile it seems that some files are missing. Iv'e tryied to re-clone everything but with no success.
Any advice?
Thanks in advance for your attention, Greg. 
![make error](https://cloud.githubusercontent.com/assets/26111747/25773884/f6330ff8-3285-11e7-9552-b890edaca02e.jpg)

**Comment by KG5IEN** [comment]
If I'm interpreting the output (and Italian) correctly, I believe it is having trouble finding arm-none-eabi-gcc, which is part of the arm toolchain.  

Did you follow the [instructions here](https://github.com/travisgoodspeed/md380tools/blob/master/docs/gnuwin32.md)?  This snippet in particular seems relevant:

> Download and install gcc-arm-none-eabi from: https://launchpad.net/gcc-arm-embedded/4.8/4.8-2014-q1-update At the end of the install, tick the 'add path to environment variable' box before clicking finish.
>
> Reboot your PC

**Comment by IZ4FXC** [comment]
Thank you for coming back to my question, yes I did and verifed the correct path variable settings too, all seems to be right.

Path: (Omissis...) ;C:\Progra~1\GnuWin32\bin;C:\Python27;C:\Program Files\Git\cmd







----Messaggio originale----

Da: "KG5IEN" <notifications@github.com>

Data: 07/05/2017 17.48

A: "travisgoodspeed/md380tools"<md380tools@noreply.github.com>

Cc: "IZ4FXC"<demichele_g@libero.it>, "Author"<author@noreply.github.com>

Ogg: Re: [travisgoodspeed/md380tools] Error in compiling. (#740)




If I'm interpreting the output (and Italian) correctly, I believe it is having trouble finding arm-none-eabi-gcc, which is part of the arm toolchain.

Did you follow the instructions here?  This snippet in particular seems relevant:


Download and install gcc-arm-none-eabi from: https://launchpad.net/gcc-arm-embedded/4.8/4.8-2014-q1-update At the end of the install, tick the 'add path to environment variable' box before clicking finish.

Reboot your PC

**Comment by KG5IEN** [comment]
I don't see the location for the arm toolchain in the path you posted.  On my machine (Windows 10 64-bit), C:\Program Files (x86)\GNU Tools ARM Embedded\4.8 2014q1\bin is the directory that is in my path that contains arm-none-eabi-gcc.exe

Is that directory (or something similar to it) in your path?  Can you find where the gcc-arm-embedded installer installed to and verify that arm-none-eabi-gcc.exe is in the bin subdirectory?

**Comment by IZ4FXC** [comment]
Yes it is (in the omitted, sorry) but a reinstallation of GNU has solved the problem, maybe something didn't work in the first installation.
Thank you very much for having pointed my attention in the correct direction.
Hope to catch you in the frequency!
IZ4FXC, Greg.




----Messaggio originale----

Da: "KG5IEN" <notifications@github.com>

Data: 07/05/2017 19.19

A: "travisgoodspeed/md380tools"<md380tools@noreply.github.com>

Cc: "IZ4FXC"<demichele_g@libero.it>, "Author"<author@noreply.github.com>

Ogg: Re: [travisgoodspeed/md380tools] Error in compiling. (#740)




I don't see the location for the arm toolchain in the path you posted.  On my machine (Windows 10 64-bit), C:\Program Files (x86)\GNU Tools ARM Embedded\4.8 2014q1\bin is the directory that is in my path that contains arm-none-eabi-gcc.exe

Is that directory (or something similar to it) in your path?  Can you find where the gcc-arm-embedded installer installed to and verify that arm-none-eabi-gcc.exe is in the bin subdirectory?
