### ISSUE TITLE
No contact list menu

### ISSUE THREAD

**Issue by hsojhcoom** [travisgoodspeed/md380tools#747]
Radio: TYT MD-380
OS: Linux Mint/ Win 10 with VM tools
Issues: Have flashed the firmware with both tools listed above. Both times it has given no menu option for contacts nor in the MDToolz Menu no option for contact list or options either. Tried first on the Win 10 with the VM tools. Ran GLV, flashed and updated db before flash db. 

Linux installed via direction on Github. No issues install, firmware install no issues (minus no contacts) Updated db, flashed db, no contacts still. Did a clean flash and flashed db with not luck

**Comment by KD4Z** [comment]
For support of the md380tools, you should post in the Google group here: https://groups.google.com/forum/#!forum/md380tools

**Comment by hsojhcoom** [comment]
There is no "User DB" Selection under the MD380tools menu......

**Comment by Wolf-DL4YHF** [comment]
..... because it has been moved into submenu "Show Calls" :o)

I think we can close this.....

Am 14.05.2017 um 00:56 schrieb Josh Mucinski:
