### ISSUE TITLE
users.csv font has chopped off characters

### ISSUE THREAD

**Issue by dysinger** [travisgoodspeed/md380tools#76]
See the screenshots in #55 for both fonts

Letters g, j, p, q & J are all chopped off at the bottom.  the J is especially problematic as it's in call signs & people's names (Jim, Jerry)

**Comment by dg9vh** [comment]
Problem was solved with https://github.com/travisgoodspeed/md380tools/pull/71

**Comment by travisgoodspeed** [comment]
Closing issue, as @dg9vh claims it was solved with #71.
