### ISSUE TITLE
Talker Assist rarely displays (MD390GPS)

### ISSUE THREAD

**Issue by kb8fk** [travisgoodspeed/md380tools#764]
First noticed on 19 May. Even if TA only is selected, I only get User DB display.

**Comment by kb8fk** [comment]
Sorry, forgot to mention that it was working more consistently before that.

**Comment by ok2it** [comment]
Can you confirm you are seeing Talker Alias data comming through frequently on screen #4 ??
This could be related to hotspot or repeater not sending TA at all or less frequently.
I have seen simillar behaviour while working over mmdvm rptr with signals on the edge.

**Comment by kb8fk** [comment]
Yes, I see the data. I have found that if I change to another channel then back during reception I get the TA display. I am running a DVMEGA/rpi3 hotspot with Mmdvmhost.

**Comment by DL2MF** [comment]
Talker alias display needs complete RX/decode of the TA header data, this may depend on your frequency offset and hotspot drift. The recent and current release (pending PR) doesn't contain any changes for TA. I have it myself in use and today received many TA frames via my local repeater without any issues.

**Comment by kb8fk** [comment]
OK, I'll check my hotspot, Mmdvmhost setup and prior firmware. If I discover anything new, I'll report back. Thanks for the feedback and for all the great work you all are doing!
