### ISSUE TITLE
Extra Top-Icons

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/md380tools#77]
We need the ability to show additional icons, indicating features such as promiscuous mode and a custom scanner.  These could go in the original row, or they might be shown along the right-hand side of the display.

**Comment by aeickho** [comment]
@all .. this is an important feature for the hamvention release :) 

and in my opinion it is quite easy to realize a beautiful project to go into the software development on the md380.

sample image: 0x80f9d20.ppm 

have fun
alex

**Comment by aeickho** [comment]
first step: create an image 12x12 pixel for the promiscuous mode

**Comment by phl0** [comment]
What about this?
![promisc](https://cloud.githubusercontent.com/assets/7112907/15126758/d7113560-1633-11e6-96eb-dfcac915785d.png)

**Comment by gadget-fan** [comment]
Or this.
![tinynose](https://cloud.githubusercontent.com/assets/12849766/15127621/067f494a-15fd-11e6-8b8c-ec1c8e00cdd8.png)

**Comment by maushammer** [comment]
I'll throw an illuminati-style pyramid eye in to the ring:
![pyramid eye](https://cloud.githubusercontent.com/assets/18044422/15127986/825e6a8e-15f6-11e6-8acc-f8d1b4177324.png)

**Comment by der-stefan** [comment]
Or this:
![test](https://cloud.githubusercontent.com/assets/3618939/15128075/0d5dd6fe-163a-11e6-8400-d49ed4332302.png)

**Comment by maushammer** [comment]
Or a magnifying glass "inspector":
![mag glass](https://cloud.githubusercontent.com/assets/18044422/15128064/ef6f61be-15f6-11e6-867b-d678f2c720c1.png)

**Comment by gadget-fan** [comment]
I like the pyramid!  There is this too.
![promiscuousmode](https://cloud.githubusercontent.com/assets/12849766/15128093/6ed74752-15ff-11e6-85d6-828682564701.png)

**Comment by der-stefan** [comment]
Or just simply an eye:
![gimp-icon_stock-eye-12](https://cloud.githubusercontent.com/assets/3618939/15128151/795cbdca-163a-11e6-9b8a-3778b9655558.png)

**Comment by phl0** [comment]
I am stuck trying to integrate this icon. Could someone assist me with integrating the icon into the firmware?

**Comment by dg9vh** [comment]
@phl0 maybe i could help you. Where exactly is the problem? have you created a ppm-file? have you modified the head of the file (if necessary)?

**Comment by phl0** [comment]
@dg9vh Jepp. Created a ppm file and changed the header to include the data of the original .ppm file. The question is how to import it back into the firmware.

**Comment by dg9vh** [comment]
Should work like replace the welcome screen shown in makefile but with other address.

**Comment by aeickho** [comment]
![c](https://cloud.githubusercontent.com/assets/986535/16708808/d4061948-45ff-11e6-9705-f2f36e3cd54b.jpg)

**Comment by travisgoodspeed** [comment]
Nice!

**Comment by aeickho** [comment]
done with f07304c2500983d044b1eb0ed2d99df90ece103e

the place to update the eye is not perfect ... but I have the location where battery, letterhead, etc. is drawn not found

**Comment by aeickho** [comment]
the Top Icon line is full, on the position of the "eye" is also the gps (locked) icon

![x](https://cloud.githubusercontent.com/assets/986535/18725733/b8344416-8041-11e6-8229-85fde200f3a4.jpg)
