### ISSUE TITLE
USB Issues when flashing users.csv

### ISSUE THREAD

**Issue by jimlaughlan** [travisgoodspeed/md380tools#776]
Getting this error when flashing the userdb. Any ideas for cause?

Exception usb.core.USBError: USBError(19, u'No such device (it may have been disconnected)') in <bound method Device.__del__ of <DEVICE ID 0483:df11 on Bus 002 Address 003>> ignored

**Comment by travisgoodspeed** [comment]
@jimlaughlan Please ask for help on the mailing ist or on the IRC channel.  This issue tracker is for known problems with the firmware; it is not a support forum.
