### ISSUE TITLE
Squelch

### ISSUE THREAD

**Issue by jasons1150** [travisgoodspeed/md380tools#778]
I am having an issue on analog to me it sounds like the squelch is too tight even on normal. The LED lights up then it's receiving a signal and depending on how I wave the radio around or hit the monitor button it will allow the audio through. Pl is right

**Comment by MeestorX** [comment]
Could this be the cause of the scanning bug?
https://www.youtube.com/watch?v=DtE1NyeDpsg

**Comment by jasons1150** [comment]
No I don't scan with it

**Comment by MeestorX** [comment]
> No I don't scan with it
So... not related, you think?

**Comment by jasons1150** [comment]
Nope to me it sound like the squelch is too tight. I cant even turn the squelch off and have it by ctcss

**Comment by jasons1150** [comment]
Or maybe I can I'll have to try that

**Comment by travisgoodspeed** [comment]
Can anyone reproduce Jason's problem on their own radio?

**Comment by MeestorX** [comment]
I can't reproduce that problem, I'll start a new thread for my particular bug.

**Comment by jasons1150** [comment]
My Kenwood tk8180 and uv5r allow the squelch to be set to a number

**Comment by jasons1150** [comment]
The signal from the repeater maybe a little on the weak side but when I hold the monitor button open it actually sounds good

**Comment by travisgoodspeed** [comment]
Regardless, this is a feature request and not a bug in our firmware patches.  Closing issue.

(Sorry neighbor; we can't fix all of Tytera's imperfections.)

**Comment by jasons1150** [comment]
Ok thanks

**Comment by jasons1150** [comment]
Where can I get you firmware I don't think I'm using your
