### ISSUE TITLE
What is SPI Flash ID: 10 dc 1    ?

### ISSUE THREAD

**Issue by oe3jtb** [travisgoodspeed/md380tools#78]
when trying to write users.csv to a MD380 UHF I get

SPI Flash ID: 10 dc 1
local variable 'size' referenced before assignment

I think this part is responsiible

def flashgetid(dfu):
    buf=dfu.spiflashgetid();
    print "SPI Flash ID: %x %x %x"%(buf[0],buf[1],buf[2])
    if (buf[0] == 0xef and buf[1] == 0x40):
        if (buf[2] == 0x18):
            sys.stdout.write("W25Q128FV 16MByte\n");
            size=16*1024*1024;
        elif (buf[2] == 0x14):
            sys.stdout.write("W25Q80BL 1MByte\n");
            size=1*1024*1024;
        else:
            sys.stdout.write("Unkown SPI Flash - please report\n");
            size=0;
    return size;

The procedure runs direct to "return size" without setting "size" to a value

Any suggestions?
tnx kind regards
Alex

**Comment by travisgoodspeed** [comment]
Howdy Alex!

The UHF model of the MD380 usually has a 16MByte W25Q128FV chip, but the VHF model carries a smaller 1MByte chip.  Your radio has a model that we haven't seen before.  Congratulations!

Could you send us some photos of your radio, or tell us more about its branding (Tytera/Retevis/TYT/NKTech/etc)?

We'll add your chip to the table in short order.

--Travis

**Comment by oe3jtb** [comment]
Hi Travis
tnx for the fast answer
so here it is
http://i.imgur.com/iziTKSt.jpg
http://i.imgur.com/Sqv3V9l.jpg
tnx
kind regards
Alex

**Comment by dg3yjb** [comment]
Hello,
the same problem is here.
Branding is Tytera.

![img_6313](https://cloud.githubusercontent.com/assets/18097245/14923317/d0395172-0e3c-11e6-9b90-d5aca59374a6.JPG)

**Comment by rct** [comment]
Just curious does that model ID make it into the .rdt or bare code plug?

**Comment by dg3yjb** [comment]
A Screenshot from the original tyter MD-380 programming tool
![md-380](https://cloud.githubusercontent.com/assets/18097245/14934889/a50ed692-0ebf-11e6-998f-de96405311fe.png)

**Comment by aeickho** [comment]
corr python error with: c52cd0641b5615152ef85056c423f10bc2517f9e

**Comment by aeickho** [comment]
one solution see: @travisgoodspeed  #66 try and error to detect the spi-flash size.

**Comment by oe3jtb** [comment]
![0501-2](https://cloud.githubusercontent.com/assets/18739945/14944393/00922ec8-0ff2-11e6-9503-b157790190fb.jpg)

Took a photo with my electronic microscope, should be the 16MB, but with other ID

**Comment by aeickho** [comment]
On e06be0fb1385d09f7dbd003f825cded5b728e072
is a test version with interpret  Flash ID: 10 dc 1 as 16MByte spi flash chip

**Comment by oe3jtb** [comment]
Hi
did a new clone
git clone https://github.com/aeickho/md380tools.git

and than the same as before
now the output from 
./md380-tool spiflashwrite data 0x100000
is


SPI Flash ID: 10 dc 1
can't programm spi flash wrong flash type

**Comment by aeickho** [comment]
git clone https://github.com/aeickho/md380tools.git
git checkout next_spi_flash

make clean


and than the same as before
now the output from
./md380-tool spiflashwrite data 0x100000
is

**Comment by oe3jtb** [comment]
ok tnx

so in line 342 there is in my opinion a typing error
def flashgetid(dfu):
    size=0;
    buf=dfu.spiflashgetid();
    print "SPI Flash ID: %x %x %x"%(buf[0],buf[1],buf[2])
    if (buf[0] == 0xef and buf[1] == 0x40):
        if (buf[2] == 0x18):
            sys.stdout.write("W25Q128FV 16MByte\n");
            size=16*1024*1024;
        elif (buf[2] == 0x14):
            sys.stdout.write("W25Q80BL 1MByte\n");
            size=1*1024*1024;
    elif (buf[0] == 0x10 and buf[1] == 0xdc):
        if (buf[2] == 0x01):
            sys.stdout.write("W25Q128FV 16MByte maybe\n");
            size=16*1024*1024;          
    else:
            sys.stdout.write("Unkown SPI Flash - please report\n");
    return size;


in original 
elfi (buf[0] == 0x10 and buf[1] == 0xdc):
^^^
I corrected to elif

and run again
after serveral erase
the last lines of the output are

1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 125 11f400 1024 
1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 126 11f800 1024 
1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 127 11fc00 1024 
1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 128 120000 1024 
1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 129 120400 1024 
1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 130 120800 1024 
1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 131 120c00 1024 
1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 132 121000 1024 
1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 133 121400 1024 
1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 134 121800 1024 
1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 135 121c00 1024 
1024
1033
(OK, 0, dfuDNLOAD_IDLE, 0)
2351 136 122000 1024 
1024
1033
[Errno 110] Operation timed out



tnx Alex

**Comment by aeickho** [comment]
if you repeat flashdb ... stopped it on the same address?

**Comment by aeickho** [comment]
please fetch the branch ... some additional function added: flash exclusive  now

**Comment by oe3jtb** [comment]
Bingo !!! all is working fine, uploaded the whole world!!!

TNX
Alex, OE3JTB

**Comment by aeickho** [comment]
I'll Patch ... The spiflash type test .. Then I close this issue..
