### ISSUE TITLE
Errno 110: Operation timed out

### ISSUE THREAD

**Issue by jamccormick** [travisgoodspeed/md380tools#786]
I keep having this problem while trying to run `make flash` with an MD-380 and the no-GPS firmware.  It won't communicate, and my radio is now bricked--it does not boot, and it does not have firmware.  

I've attached a dump of the program output when I run `make flash`.  Any advice would be appreciated.

Additionally, I get the same timed out error when trying to run md380-tool dmesg.  I can't get information in or out of the radio.

##Support materials

* The output of `make flash`: [output.txt](https://github.com/travisgoodspeed/md380tools/files/1082771/output.txt)
* The output of `md380-tool calibration: [calibration.txt](https://github.com/travisgoodspeed/md380tools/files/1082773/calibration.txt)
* SPI dump: `Dumping SPI Flash to 'spidump.bin'.  The device has no langid`

I can't get any other information--it isn't there.  I'll get pipe errors, which seems to indicate that the file it's looking for isn't there.

**Comment by roelandjansen** [comment]
Reflashing with windows one time does not work?

To me it sounds like your build env is b0rked.

**Comment by DL2MF** [comment]
Check your programming cable at the USB-connector side, looks like broken.

**Comment by DL2MF** [comment]
@jamccormick @travisgoodspeed This is no sw issue, flashing MD-380 works fine, like just confirmed with a unit. May be closed.

**Comment by jamccormick** [comment]
Confirming: not an issue with software. Close it. 

Replacing the cable fixed the problem.
