### ISSUE TITLE
awk overflow now that dmr-marc line count over 65535 lines

### ISSUE THREAD

**Issue by KD4Z** [travisgoodspeed/md380tools#794]
It appears that awk has a line count limit.   I can't find hard evidence fingering awk yet, but it seems to be a 16-bit overflow.  Getting an invalid pointer overflow when creating stripped.csv, now that the dmr-marc download is over 64K   The step that combines and de-dups the data is now bonking.

stripped.csv: custom.csv special.tmp fixed.csv dmrmarc2.tmp reflector.tmp
	awk -F, -f combine.awk $^ | $(ICONV)  | sort -t ',' -k1g,1 | awk -F, -f strip.awk >stripped.csv	

combine.awk is a duplicate row reducer, strip.awk seems to just manipulate in an extra field for country.  Some refactoring around the awk limitation is needed.   I'm poking around for a substution now, but figured I'd open this to bring this up to the Team to help knock this out fast.

**Comment by KD4Z** [comment]
It seems to be just the combine.awk step that is overflowing.  Since it looks like it's just a file concat step (not a de-dup pass as I first thought) , I changed the target to this less elegant solution and it stopped overflowing.  Odd that the last pass through awk with strip.awk doesn't overflow.

Anyone have any issue with this brute force workaround before I make a PR?

original:
awk -F, -f combine.awk $^ | $(ICONV)  | sort -t ',' -k1g,1 | awk -F, -f strip.awk >stripped.csv

to:
cat custom.csv special.tmp fixed.csv dmrmarc2.tmp reflector.tmp | $(ICONV) | sort -t ',' -k1g,1 | awk -F, -f strip.awk >stripped.csv

**Comment by travisgoodspeed** [comment]
We really ought to ditch the awk scripts for something sturdier, but in the meantime, please do send along a pull request for the quick fix.

**Comment by KD4Z** [comment]
ok, it's on the way.

**Comment by sijskes** [comment]
Proposed solution does not filter duplicates in order.

The original solution is meant to allow local overrides in custom.csv.

Yours provides random selection of either a override or one from the 
remote db.

**Comment by travisgoodspeed** [comment]
@sijskes Is this issue good to close, or do bugs remain?

**Comment by KD4Z** [comment]
@travisgoodspeed @sijskes   The original author's awk script was overflowing on a Cast of the placeholder in the de-dup array.  This placeholder contained no real value other allowing the element to be created in the array-- it's existence in the array being testable detection of further dups.    I removed the Cast by simply assigning a numeric instead of "x"      I believe it has been resolved for now and should be closed.

**Comment by sijskes** [comment]
the patch does remove the override function, where you can override a record manually. 
so i believe it is not a good fix.

**Comment by sijskes** [comment]
but the problem has been solved elsewhere, so i close this.

**Comment by KD4Z** [comment]
>the patch does remove the override function, where you can override a record manually.
>so i believe it is not a good fix.
@sijskes @travisgoodspeed    Just how do you come to that conclusion?   The final PR does not remove that intended de-dup functionality at all.   It was solved here, not elsewhere.
