### ISSUE TITLE
Menu Label Cosmetic 

### ISSUE THREAD

**Issue by aeickho** [travisgoodspeed/md380tools#80]
At the moment, this texts are included:
static wchar_t wt_addl_func[]         = L"Addl. Funct";
static wchar_t wt_datef[]             = L"Date format";
static wchar_t wt_debug[]             = L"Debug";
static wchar_t wt_disable[]           = L"Disable";
static wchar_t wt_enable[]            = L"Enable";
static wchar_t wt_rbeep[]             = L"M. RogerBeep";
static wchar_t wt_userscsv[]          = L"UsersCSV";
static wchar_t wt_datef_original[]    = L"Original";
static wchar_t wt_datef_germany[]     = L"German";
static wchar_t wt_promtg[]            = L"Promiscuous";
static wchar_t wt_edit[]              = L"Edit";
static wchar_t wt_edit_dmr_id[]       = L"Edit DMR-ID";
static wchar_t wt_no_w25q128[]        = L"No W25Q128";

Please support me to find the correct words.

**Comment by oe3jtb** [comment]
static wchar_t wt_rbeep[] = L"M. RogerBeep";
static wchar_t wt_datef_original[] = L"Original";
static wchar_t wt_datef_germany[] = L"German";

My suggestion
static wchar_t wt_rbeep[] = L"Smooth Beep";
static wchar_t wt_datef_original[] = L"YYYYDDMM";
static wchar_t wt_datef_germany[] = L"YYYYMMDD";


What does ?
static wchar_t wt_debug[] = L"Debug"
static wchar_t wt_promtg[] = L"Promiscuous";

73 Alex

**Comment by dg9vh** [comment]
when german it is: 
static wchar_t wt_datef_germany[] = L"DD.MM.YYYY";

**Comment by jruys** [comment]
I have

Date Format
YYYY/MM/DD
DD/MM/YYYY (I changed the code locally to use "/" in stead of ".")

Don't think there's an ISO name for the various modes. I'm sure the US folk will ask for MM/DD/YYYY
