### ISSUE TITLE
CPS + Talkalias

### ISSUE THREAD

**Issue by Arander** [travisgoodspeed/md380tools#800]
Hi everyone

Is it possible to have a "CPS & Talkalias" option under the "Show Call" menu entry?

I have a VHF MD380 and since it has the small flash memory, I cannot upload the userDB to the radio. However, I do have all users in my country as contacts in the CPS. Still, for other users, I notice that sometimes I can still get their callsigns (more correctly, their talkalias) if I select "TA & userdb".

So, it would be nice to have a "CPS & Talkalias" in order to get the information from either or both sources.

Thanks and good work, the "tools" is a wonderful mod to the radio

73 de CE3SNA

**Comment by DL2MF** [comment]
Hi,

the current screen display doesn't have access to the CPS name, when selecting CPS in "Show Calls" the genuine firmware display screen is selected to display user information.

All other modes are depending on our MD380tools display routines and using information from the network data (TA) or user database. Maybe I'll look for another method in a later release, but currently this is not on my priority list.

73 Mike, DL2MF
