### ISSUE TITLE
Raspberrypi 2 make: *** [flashdb] Error 1

### ISSUE THREAD

**Issue by dgreene128** [travisgoodspeed/md380tools#803]
I'm receiving the following error when trying to update my database on MD380tools:

awk -F, -f combine.awk custom.csv special.tmp fixed.csv dmrmarc2.tmp reflector.tmp | iconv -c -f UTF-8 -t ascii//TRANSLIT  | sort -t ',' -k1g,1 | awk -F, -f strip.awk >stripped.csv
make[2]: Leaving directory '/home/pi/md380tools/db'
make[1]: Leaving directory '/home/pi/md380tools/db'
"make" -C db stripped.csv
make[1]: Entering directory '/home/pi/md380tools/db'
make[1]: 'stripped.csv' is up to date.
make[1]: Leaving directory '/home/pi/md380tools/db'
wc -c < db/stripped.csv > user.bin
cat db/stripped.csv >> user.bin
./md380-tool spiflashwrite user.bin 0x100000
'Device' object has no attribute 'manufacturer'
Makefile:97: recipe for target 'flashdb' failed
make: *** [flashdb] Error 1

Firmware flashed just fine.  I'm not in the USB mode on the MD380 when running 
 sudo make updatedb flashdb

**Comment by travisgoodspeed** [comment]
Please send support requests to the mailing list or the IRC channel.  You probably have your radio booted to the wrong mode or are missing the udev rules, but this isn't the place to discuss it.
