### ISSUE TITLE
VOX hang time setting

### ISSUE THREAD

**Issue by Wopley** [travisgoodspeed/md380tools#804]
It would be great if VOX had an adjustable hangtime that holds the PTT open for a given period of time giving you a chance to pause while speaking.
Currently, radio waits for incredibly long time (3-5s) before hanging up after voice transmission is over and there is no visible way to change this.

**Comment by travisgoodspeed** [comment]
This is an issue tracker, not a feature request form.  Please post feature requests to the mailing list instead.

73 from New York,
-KK4VCZ
