### ISSUE TITLE
New roger tone

### ISSUE THREAD

**Issue by MM6HHP** [travisgoodspeed/md380tools#811]
Hi there
Is there any chance of a new roger tone and PTT ID that is likened to that of a motorola or sepura tetra radio

If there is any chance this is possible it would be very much appreciated as the stock tone is getting rather irritating at the moment

Thanks in advance 
Rylan Jenkins

**Comment by mach327** [comment]
I wish, I find it annoying also. Lately I just keep the tones off.

That said, this is an issue tracker, not a feature request form.
Please post feature requests to the mailing list (linked above) instead.
