### ISSUE TITLE
Menus are incorrectly indicated for mic bargraph and prom. mode.

### ISSUE THREAD

**Issue by KE7EVP** [travisgoodspeed/md380tools#812]
After ea0a985,microphone bargraph and promiscious are permanently disabled,and experimental is permanently enabled.

**Comment by mach327** [comment]
Would you say it works, just when you re-enter the menu it incorrectly indicates a different currently-selected value?
That's what I'm getting for mic bargraph and promiscuous mode, it seems like.

**Comment by travisgoodspeed** [comment]
Fixed in #813.  Closing issue.

**Comment by stargo** [comment]
Ah, according to this issue it's also wrong for the experimental menu.
I didn't see that before. I'll fix it, test it and make a new pull request in a short while.
