### ISSUE TITLE
experimental/promiscuous 4eba047

### ISSUE THREAD

**Issue by KE7EVP** [travisgoodspeed/md380tools#822]
Experimental can't be disabled, promiscuous can't be enabled in new build.

**Comment by travisgoodspeed** [comment]
Please include more detail.  I don't understand what you are reporting.

**Comment by KE7EVP** [comment]
It's an md380In the menu experimental mode can't be disabled and promiscuous mode can't be enabled
 

    On Sunday, October 15, 2017, 12:06:18 PM PDT, Travis Goodspeed <notifications@github.com> wrote:  
 
 
Please include more detail. I don't understand what you are reporting.

**Comment by ztechire** [comment]
Hi, I would have appear to have a simila problem, Eithe promicuous is not working or squelch is not opening. I am not receiving anything.

**Comment by travisgoodspeed** [comment]
Confirmed the issue.

**Comment by ztechire** [comment]
Great.

**Comment by ztechire** [comment]
Update, I have now got scanning and promiscuous mode working but only if the RX & TX freqs are not the same. Is this the way it is meant to work ?

**Comment by DL2MF** [comment]
I'll have a look on this soon while preparing the next build.
