### ISSUE TITLE
Demo Screen Enable/Disable is reversed.

### ISSUE THREAD

**Issue by Ramsin** [travisgoodspeed/md380tools#824]
Hello all,

When selecting to enable/disable the Demo Screen under Boot Options...if you selected Enable, the Disable button is filled in and vice versa.

**Comment by docprofsky** [comment]
I have the same issue. I am running c7114fe.

**Comment by docprofsky** [comment]
I believe this issue was introduced with this change.
https://github.com/docprofsky/md380tools/commit/da69436af3adc63ee09e24cdd812a04e82215d1a#diff-9750c96407ee9f6d4e19ac7861ea8484L527

**Comment by travisgoodspeed** [comment]
Yup, that's the culprit.  Swapping the order back ought to fix it.

/cc @DL2MF

**Comment by DL2MF** [comment]
Tnx, will be fixed soon with next build. @travisgoodspeed
