### ISSUE TITLE
 UserDB over 5 MB

### ISSUE THREAD

**Issue by PD1LOI** [travisgoodspeed/md380tools#832]
Mike any time one now the userdb. bin load goes in you firmware then it goes wrong. Apparently the firmware yet accommodate more than 5 MB data for the userdb.

**Comment by PD1LOI** [comment]
Wrong person.

**Comment by PD1LOI** [comment]
Mistake of mine.

**Comment by DL2MF** [comment]
Has been already increased up to 7MB by #827, maybe closed.

**Comment by travisgoodspeed** [comment]
Closing.  Before it gets much larger, we probably ought to look at compressing the database.

**Comment by KD4Z** [comment]
Working on that now.   I have a simple abbreviation of the top 10 occuring country names with re-expansion in display.c that has achieved an instant 11% reduction.  This is live in my current Toolkit VM based builds.   However, working with another dev on a brute force compression of similar phrases, that has achieved a user.bin that is 58% of original size, but with a long compression time.  So, it's still a work is in progress.

**Comment by travisgoodspeed** [comment]
Cool.  If the compression time needs to be long, we can mirror a precompressed database.
