### ISSUE TITLE
False Encryption State

### ISSUE THREAD

**Issue by onemikedelta** [travisgoodspeed/md380tools#842]
My MD390G is not sending/setting necessary fields on the air when i turn on encryption. I am monitoring using DSD+ and it always displays Group Call, not Enc Group Call as i see when i monitor other frequencies. It also tries to decrypt clear communication and produces stupid sounds. Same for both basic and enhanced privacy.

I installed  MD380 Tools 2.0 2018-01-02 CP Ver: V01.34

**Comment by travisgoodspeed** [comment]
This sounds like a bug in the original firmware.
