### ISSUE TITLE
Typo in UserDB?

### ISSUE THREAD

**Issue by Ciava** [travisgoodspeed/md380tools#843]
Hello. 
This is a really minor issue. I found that when I'm receiving signals from repeater I get the caller ID and he's from "Italu". When he stops talking, screen gets grey for a moment and text changes to "Italy". There must me some typo in the database! (I think!)

![italu](https://user-images.githubusercontent.com/8193035/35001117-62567840-fae6-11e7-9897-7b1b25a835a9.jpg)

![italy](https://user-images.githubusercontent.com/8193035/35001116-622b09bc-fae6-11e7-9954-d9e16a6d3cc1.jpg)

**Comment by travisgoodspeed** [comment]
The bottom of the Y is overwritten by a GUI artifact at the bottom of the screen.

I'm triaging this was "wontfix" because it's a minor problem that will involve lots of GUI work to fix.  Re-open if an easier cause or fix is found.
