### ISSUE TITLE
Error when trying to make on locales folder

### ISSUE THREAD

**Issue by joyel24** [travisgoodspeed/md380tools#850]
Here is the output error when I try to compile locales : 
Makefile:30: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

I tried with Both macOS and Debian Stretch

**Comment by travisgoodspeed** [comment]
This looks like the fault of a bad pull request for French localization.  Please know that localization is incomplete and unsupported, but I'll be pushing a fix to the Makefile in a jiffy.

**Comment by joyel24** [comment]
@travisgoodspeed Ok Thanks for your reply, I was able to build it manualy with the commands shown on the makefile. But yeah I know that it's not yet working properly.

**Comment by travisgoodspeed** [comment]
It's all fixed now.
