### ISSUE TITLE
DMR-ID change not persistent after power off

### ISSUE THREAD

**Issue by dg9vh** [travisgoodspeed/md380tools#86]
If one changes the DMR-ID via utilities - addl. funct. the DMR-ID only stays until power-cycle. Then the original DMR-ID from the codeplug is in use again.

Is this a bug or a feature? Could be both, hi.

**Comment by travisgoodspeed** [comment]
This was intentionally done that way to avoid risks of damaging the codeplug through an improper write. Now that SPI Flash writes are stable, we can write this back to the codeplug.

Close this issue when the changed LLID is permanent.

**Comment by dg9vh** [comment]
I'll do so!

**Comment by aeickho** [comment]
fixed with: ff484b59e98faa8c9e0c487ef569f74136462951
