### ISSUE TITLE
Feature-Documentation in German

### ISSUE THREAD

**Issue by dg9vh** [travisgoodspeed/md380tools#88]
Take a look at https://wiki.dg9vh.de/dmr:tytera_tyt_md-380:experimentelle_firmware_von_travis_goodspeed_-_kk4vcz

Maybe you'll refer at it in README.md for german-speaking-users.

I would take this page actual with development as it is possible for me...

**Comment by der-stefan** [comment]
Thank you for sharing this! I think it would be a good idea to write something similar for the project on Github itself.

**Comment by aeickho** [comment]
i work on it 
https://github.com/aeickho/md380tools/edit/menu/README.de.md

**Comment by der-stefan** [comment]
Perfect! Thanks alot.

**Comment by aeickho** [comment]
feel free to contribute

**Comment by dg9vh** [comment]
Why not use github wiki?

**Comment by dg9vh** [comment]
Alex, you can take all of my text into it...
