### ISSUE TITLE
Battery Percentage / Voltage indication

### ISSUE THREAD

**Issue by pwrsoft** [travisgoodspeed/md380tools#889]
It would be cool if we can see Battery Percentage [Voltage] indication somewhere on the screen.
That will allow us to estimate the remaining charge capacity on the spot.
As well as prolong battery life by keeping the battery charge [40-80%](https://www.csmonitor.com/Technology/Tech/2014/0103/40-80-rule-New-tip-for-extending-battery-life) rule.

**Comment by travisgoodspeed** [comment]
Moved to #370.  We'll reopen this if anyone begins work on the feature.
