### ISSUE TITLE
1750 Hz tone

### ISSUE THREAD

**Issue by der-stefan** [travisgoodspeed/md380tools#89]
Add the option to send a 1750 Hz tone by pressing one of the side buttons.

**Comment by aeickho** [comment]
I think, this is possible - not now but in the near future

**Comment by der-stefan** [comment]
The DTMF tones are generated in the STM32 and feed out on PC8 (pin 65) and feed into the C5000 on MIC2_P (pin 5). The same path could probably be used for a 1750 Hz tone.

**Comment by travisgoodspeed** [comment]
Thanks, Stefan!  If PC8 is raw audio, we might be able to use it for APRS transmissions on the VHF model!

(But dear Lord, don't create an issue for that until we have this much working.)

**Comment by der-stefan** [comment]
@travisgoodspeed I haven't measured the pins, my statement is based on the schematic. And it would make sense: The STM32F405 has a timer (TIM8, CH3) there. Directly after the pin comes a small lowpass filter. I bet, the pin is already used in the function of a timer for creating the DTMF tones.

**Comment by der-stefan** [comment]
There could also be the possibility to completely bypass the C5000 by using the CTCSS/DCS output of the STM (PC7, Pin 64). This signal is directly feeded to the modulator! So there is the chance of generating signals only with the microcontroller.

**Comment by aeickho** [comment]
the 1750 Hz tone is added by Retevis with d13.020 ... enable it on cps 1.32

**Comment by aeickho** [comment]
see #218

**Comment by der-stefan** [comment]
Great news! Perhaps the Chinese read our issue here...
