### ISSUE TITLE
Status LED signaling

### ISSUE THREAD

**Issue by der-stefan** [travisgoodspeed/md380tools#90]
It would be a nice feature to blink the green LED every 10 seconds to show that the radio is switched on. Since the display turns off after a certain time there is the risk of forgetting the radio, until it turns itself off by a drained battery.

**Comment by der-stefan** [comment]
Now it happened to myself: Over night my "Tüte" was switched on accidentally, because I didn't realize it. Either the LED should blink every few seconds, or we should have the option to dim the screen.
(Hopefully my battery was not deep discharged!)

**Comment by travisgoodspeed** [comment]
Merged into #370.  Reopen only if there is active progress in adding such a feature.

**Comment by Wolf-DL4YHF** [comment]
Trivial to implement now since there is a 'hooked' SysTick_Handler() for the backlight control, and (coming soon) Morse code output. Is there still some interest in this feature ?
( I personally prefer the dimmed backlight, to see the radio is still on )
