### ISSUE TITLE
UV390 Support

### ISSUE THREAD

**Issue by berkin88** [travisgoodspeed/md380tools#906]
Anyone try with Tyt MD-UV390?

**Comment by travisgoodspeed** [comment]
Dual band radios are not supported by md380tools.  Sorry.

**Comment by nemanjan00** [comment]
I fucked up and flashed mine. Any way to fix it?

**Comment by rogerclarkmelbourne** [comment]
Just use the official firmware loader to re-flash the official firmware

**Comment by nemanjan00** [comment]
I do not have access to windows machine. Only linux. Any other ideas? (or do I need to install windows)

**Comment by rogerclarkmelbourne** [comment]
I don't know if any of the tools will upload the official firmware.

You could look at https://github.com/v0l/radio_tool  but I don't know if it supports the UV-380

Probably your best bet would be to find an old Windows computer and use that, or perhaps use a VM.
However the VM will need to support accessing the USB HID device that the radio enumerates as

**Comment by nemanjan00** [comment]
Thanks. I did flash it, but, it is locked now

**Comment by rogerclarkmelbourne** [comment]
Not sure what you mean

AFIK the bootloader is not changed by the application firmware. 

So its unlikely you completely bricked the radio

The radio will always enter the bootloader if you power it with the buttons on the side pressed in.

You will see it enumerate as a USB HID device (I don't know the VID and PID).

**Comment by nemanjan00** [comment]
It is asking for password

**Comment by rogerclarkmelbourne** [comment]
What is ?

**Comment by nemanjan00** [comment]
Radio turns on now, after flashing original firware, but, it is asking for password

**Comment by rogerclarkmelbourne** [comment]
That's because your codeplug has a password set in it.

Try reloading your codeplug again.

BTW. 
I don't know if it is possible to write a codeplug to the radio when its asking for a password.

**Comment by nemanjan00** [comment]
`editcp` saved me :D
https://www.farnsworth.org/dale/codeplug/editcp/

**Comment by rogerclarkmelbourne** [comment]
OK.
