### ISSUE TITLE
RX Won't Work Unless Menu Button Pressed

### ISSUE THREAD

**Issue by notpike** [travisgoodspeed/md380tools#909]
Hi,

I'm working with a TYT MD-380 with the latest firmware and I'm experiencing something odd and I would like some advice.

While RXing traffic from either a DMR Repeater or Hotspot (NetMon and promiscuous on or off) most radio traffic doesn't get demodulated unless I hit the menu button. It's inconsistent so I'm not sure if this is a sensitivity problem with the radio (some singles are too week to get picked up) or something else like the RX function hanging up.

Any advice would be appreciated.
Thanks!

**Comment by KD4Z** [comment]
This might be related to issue #904.   You might give this a try as a possible workaround.   [https://github.com/KD4Z/md380tools-vm/raw/master/Version_5_Hardware_with_MD380tools_firmware.pdf](url)

**Comment by notpike** [comment]
Yep I believe that's the same problem I've been experiencing!
May also just have a bum radio as well lol.

Thanks!
