### ISSUE TITLE
Issue with the csv display

### ISSUE THREAD

**Issue by zarya** [travisgoodspeed/md380tools#91]
![image](https://cloud.githubusercontent.com/assets/387694/15040908/809a8a5c-12b8-11e6-9c19-54634d57668b.png)

Capital J does not display correct

**Comment by aeickho** [comment]
hy @zarya  this  is fixed with  88a9dd6577d1ef5d3f065626056fdfb64691aa2c and 1ee42e95cc06a320f201513e71cde8ef2f19cf19 .. please sync to the head 

-alex
