### ISSUE TITLE
Change DTMF tone <-> key mapping

### ISSUE THREAD

**Issue by der-stefan** [travisgoodspeed/md380tools#92]
Currently the DTMF tones are mapped in a weird way:
```
C A B D
1 2 3 *
4 5 6 0
7 8 9 #
```
It would be a nice improvement to change the mapping to an alternative:
```
A B C D
1 2 3 *
4 5 6 0
7 8 9 #
```

**Comment by travisgoodspeed** [comment]
Merged into #370.  Reopen only if there is active progress in adding such a feature.
