### ISSUE TITLE
encryption

### ISSUE THREAD

**Issue by jimgillo** [travisgoodspeed/md380tools#929]
Hello Travis,
You say in the aes.file
_ /* The key has more than its least-significant byte set, so we'll
     use the original Tytera algorithm.  At some point, it might make
     sense to replace this with proper crypto, rather than XOR._

1-Why don't you modify the code to use better crypto?
2-If you don't want to modify the code, could you add an hook to access to the code where the AES 49 bits stream is XOR'ed with the audio?

For example if i want to use AES in CFB or CBC mode i must modify the code where the AES stream is XOR'ed with the audio, but there is no such hook in the MD3800 tools.

**Comment by travisgoodspeed** [comment]
Enough hooks should be available to add better crypto, but I'm busy with other projects and won't be implementing it myself.
