### ISSUE TITLE
Why can't I patch boot "Welcome" screen exactely?

### ISSUE THREAD

**Issue by DE8MSH** [travisgoodspeed/md380tools#930]
In older versions of this hacked fw we could change boot "Welcome" to cool custom welcome screen. I didn't understand why this doesn't work any more. I read https://github.com/travisgoodspeed/md380tools/issues/221 and understood nothing. Why should "I'll close it. we understand gfx_drawbmp()" be the answer to the non patchable welcome screen?

**Comment by travisgoodspeed** [comment]
The welcome screen was first patched as an early demo, but because it's not functional, the feature wasn't ported to new versions of the firmware.
