### ISSUE TITLE
RAS support

### ISSUE THREAD

**Issue by s58sms** [travisgoodspeed/md380tools#938]
Hello,

i would like to ask developers, if there is any possibility, that custom firmware would ignore RAS (MotoTrbo) header, just like OPENGD77 does? I have tried some CAP+ with RAS turned on in my area and md380tools doesn't let voice through - apparently it messes up the header and netmonitor says rx/csbk or sth like that. This would be a very good move on with this firmware, because I have seen many requests on a web, people asking if this is possible. As we know, for example dsd+ or some scanners just ignore those header, so it's possible that you hear clear voice.

Thank you for the information.

Best regards

**Comment by 7AAZ** [comment]
@s58sms Hello, 
This feature would be very good, it is sorely missed...
Many thanks to the developers for what they've already done! Please include more of this feature
Many Thanks!
