### ISSUE TITLE
Possibility to tunr off a startup sound

### ISSUE THREAD

**Issue by bilbolodz** [travisgoodspeed/md380tools#99]
Start up sound is quite loud and annoying in some situation. I think it could be useful to have possibility to turn it off.

**Comment by der-stefan** [comment]
This is already possible with the stock firmware: Menu -> Utilities -> Tones/Alerts

**Comment by bilbolodz** [comment]
Indeed, thanks.

**Comment by bilbolodz** [comment]
Strange thing: when I turned off "all tunes/alerts" I can't hear conversation at all. It's very strange but it looks that this menu is quite useless.
